import type { WorkflowRequest } from "@/lib/workflowStore";

export type ClientServiceCategoryId =
  | "consultation"
  | "contracts"
  | "case-study"
  | "legal-filing"
  | "arbitration"
  | "special";

export type ClientServicePriceMode =
  | "free"
  | "included"
  | "fixed"
  | "starting_from"
  | "custom"
  | "per_page";

export type ClientServiceVisibility = "public" | "beta_hidden" | "internal";

export type ClientServiceCatalogItem = {
  serviceId: string;
  categoryId: ClientServiceCategoryId;
  label: string;
  description: string;
  basePrice: number;
  priceMode: ClientServicePriceMode;
  priceNote?: string;
  route: string;
  icon: string;
  receiverType: WorkflowRequest["receiver"];
  requestType: WorkflowRequest["type"];
  betaVisibility: ClientServiceVisibility;
  requiresPayment: boolean;
  enabled?: boolean;
  includedByPlan?: "free_daily" | "ai_individual" | "legal_protection" | "group";
  tag?: string;
  aiPowered?: boolean;
  humanService?: boolean;
};

export type ClientServiceCategory = {
  categoryId: ClientServiceCategoryId;
  label: string;
  description: string;
  icon: string;
  color: string;
  bgLight: string;
  borderColor: string;
  betaVisibility: ClientServiceVisibility;
};

export const CLIENT_SERVICE_CATEGORIES: ClientServiceCategory[] = [
  {
    categoryId: "consultation",
    icon: "ChatCircle",
    label: "استشارة قانونية",
    description: "اسأل محاميا مرخصا أو نظامي AI في دقائق",
    color: "from-[#0B3D2E] to-[#125340]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
  {
    categoryId: "contracts",
    icon: "FileText",
    label: "عقود ووثائق",
    description: "صياغة أو تحليل العقود بالذكاء الاصطناعي أو مراجعة من محام متخصص",
    color: "from-[#0B3D2E] to-[#125340]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
  {
    categoryId: "case-study",
    icon: "MagnifyingGlass",
    label: "دراسة وتقييم القضية",
    description: "اعرف موقفك القانوني قبل أي تحرك",
    color: "from-[#1e3a5f] to-[#2563a8]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
  {
    categoryId: "legal-filing",
    icon: "Gavel",
    label: "تحرير دعوى أو مذكرة",
    description: "صياغة لوائح ومذكرات قانونية مكتوبة لرفعها أمام الجهات القضائية",
    color: "from-[#0B3D2E] to-[#125340]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
  {
    categoryId: "arbitration",
    icon: "Scales",
    label: "تحكيم ووساطة",
    description: "حل النزاعات بطريقة أسرع وأقل تكلفة من المحاكم",
    color: "from-[#7c2d12] to-[#c2410c]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
  {
    categoryId: "special",
    icon: "ShieldStar",
    label: "خدمات خاصة",
    description: "خدمات إجرائية ومتخصصة تحتاج تنسيقا بشريا",
    color: "from-[#0B3D2E] to-[#125340]",
    bgLight: "bg-white",
    borderColor: "border-slate-200",
    betaVisibility: "public",
  },
];

export const CLIENT_SERVICE_CATALOG: ClientServiceCatalogItem[] = [
  {
    serviceId: "ai-consult",
    categoryId: "consultation",
    label: "سؤال AI فوري",
    description: "إجابة قانونية ذكية خلال ثوان - متاح 24/7 بدون حجز",
    basePrice: 49,
    priceMode: "free",
    priceNote: "لك سؤال واحد مجانا يوميا أو 49 ر.س إضافي",
    route: "/ai/consult",
    icon: "Robot",
    receiverType: "ai_workspace",
    requestType: "consultation",
    betaVisibility: "public",
    requiresPayment: false,
    includedByPlan: "free_daily",
    tag: "الأسرع",
    aiPowered: true,
  },
  {
    serviceId: "video-short",
    categoryId: "consultation",
    label: "استشارة مرئية مختصرة (30 دقيقة)",
    description: "سؤال واحد مركز مع محام متخصص عبر الفيديو",
    basePrice: 500,
    priceMode: "fixed",
    priceNote: "مرئية أونلاين - 30 دقيقة",
    route: "/dashboard/client/consultation/new?type=video-short",
    icon: "VideoCamera",
    receiverType: "lawyer",
    requestType: "consultation",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "video-full",
    categoryId: "consultation",
    label: "استشارة مرئية كاملة (60 دقيقة)",
    description: "جلسة تفصيلية عبر الفيديو مع ملخص PDF بعدها",
    basePrice: 500,
    priceMode: "fixed",
    priceNote: "مرئية أونلاين - 60 دقيقة",
    route: "/dashboard/client/consultation/new?type=video-full",
    icon: "VideoCamera",
    receiverType: "lawyer",
    requestType: "consultation",
    betaVisibility: "public",
    requiresPayment: true,
    tag: "الأشمل",
    humanService: true,
  },
  {
    serviceId: "in-person",
    categoryId: "consultation",
    label: "استشارة حضورية (60 دقيقة)",
    description: "في مكتب المحامي مع ملخص PDF رسمي بعد الجلسة",
    basePrice: 700,
    priceMode: "fixed",
    priceNote: "حضوري في مكتب المحامي",
    route: "/dashboard/client/consultation/new?type=in-person",
    icon: "Users",
    receiverType: "lawyer",
    requestType: "consultation",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "written-opinion",
    categoryId: "consultation",
    label: "رأي قانوني مكتوب",
    description: "تقرير قانوني مكتوب موقع من محام معتمد وصالح للاستشهاد به",
    basePrice: 250,
    priceMode: "fixed",
    priceNote: "يسلم خلال 2-3 أيام عمل",
    route: "/dashboard/client/consultation/new?type=written-opinion",
    icon: "FileText",
    receiverType: "lawyer",
    requestType: "consultation",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "contract-draft",
    categoryId: "contracts",
    label: "صياغة عقد مخصص",
    description: "الذكاء الاصطناعي يصيغ عقدك من البداية حسب احتياجاتك الدقيقة",
    basePrice: 99,
    priceMode: "included",
    priceNote: "أو ابتداءً من ٩٩ ر.س للطلب",
    route: "/ai/contract-drafter",
    icon: "PencilSimple",
    receiverType: "ai_workspace",
    requestType: "ai_draft",
    betaVisibility: "public",
    requiresPayment: false,
    includedByPlan: "ai_individual",
    tag: "الأكثر طلبا",
    aiPowered: true,
  },
  {
    serviceId: "ai-letter",
    categoryId: "contracts",
    label: "صياغة خطاب رسمي بالذكاء الاصطناعي",
    description: "إنذار، إخطار، مطالبة، اعتراض - أدخل التفاصيل والـ AI يصيغ خطابك في دقيقة",
    basePrice: 49,
    priceMode: "included",
    priceNote: "أو 49 ر.س للخطاب",
    route: "/dashboard/client/letters",
    icon: "Envelope",
    receiverType: "ai_workspace",
    requestType: "ai_draft",
    betaVisibility: "public",
    requiresPayment: false,
    includedByPlan: "ai_individual",
    tag: "جديد",
    aiPowered: true,
  },
  {
    serviceId: "contract-analyze",
    categoryId: "contracts",
    label: "تحليل عقد وكشف المخاطر",
    description: "ارفع عقدك ونحلله ونحدد البنود الخطرة ومواطن الضعف",
    basePrice: 79,
    priceMode: "included",
    priceNote: "أو 79 ر.س للتحليل المفصل",
    route: "/ai/analyze?mode=doc",
    icon: "Scan",
    receiverType: "ai_workspace",
    requestType: "ai_draft",
    betaVisibility: "public",
    requiresPayment: false,
    includedByPlan: "ai_individual",
    aiPowered: true,
  },
  {
    serviceId: "contract-review",
    categoryId: "contracts",
    label: "مراجعة من محام متخصص",
    description: "محام متخصص يراجع عقدك ويقدم تقريرا قانونيا مكتوبا",
    basePrice: 800,
    priceMode: "starting_from",
    priceNote: "2x سعر مراجعة المحامي",
    route: "/dashboard/client/requests/new?type=contract-review",
    icon: "MagnifyingGlass",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "ai-case-eval",
    categoryId: "case-study",
    label: "تقييم أولي بالذكاء الاصطناعي",
    description: "أدخل تفاصيل قضيتك ونحلل نقاط القوة والضعف ونقدر فرص النجاح",
    basePrice: 79,
    priceMode: "free",
    priceNote: "مشمول في الباقة أو 79 ر.س",
    route: "/ai/analyze?mode=eval",
    icon: "Robot",
    receiverType: "ai_workspace",
    requestType: "ai_draft",
    betaVisibility: "public",
    requiresPayment: false,
    includedByPlan: "free_daily",
    tag: "جديد",
    aiPowered: true,
  },
  {
    serviceId: "case-study",
    categoryId: "case-study",
    label: "دراسة قضية كاملة",
    description: "محام متخصص يدرس ملف قضيتك ويقدر فرص النجاح والمخاطر القانونية",
    basePrice: 1600,
    priceMode: "starting_from",
    priceNote: "2x سعر المحامي الأساسي",
    route: "/dashboard/client/requests/new?type=case-study",
    icon: "Scales",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    tag: "موصى به",
    humanService: true,
  },
  {
    serviceId: "second-opinion",
    categoryId: "case-study",
    label: "رأي ثان في قضية قائمة",
    description: "لديك محام بالفعل؟ احصل على تقييم مستقل من محام آخر",
    basePrice: 600,
    priceMode: "starting_from",
    priceNote: "2x سعر الرأي القانوني المكتوب",
    route: "/dashboard/client/requests/new?type=second-opinion",
    icon: "Users",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "legal-research",
    categoryId: "case-study",
    label: "بحث قانوني متخصص",
    description: "بحث في الأنظمة واللوائح والأحكام القضائية ذات الصلة بقضيتك",
    basePrice: 800,
    priceMode: "starting_from",
    priceNote: "2x سعر البحث القانوني",
    route: "/dashboard/client/requests/new?type=legal-research",
    icon: "MagnifyingGlass",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "file-lawsuit",
    categoryId: "legal-filing",
    label: "لائحة دعوى ابتدائية",
    description: "تحرير لائحة دعوى جديدة أمام المحكمة المختصة",
    basePrice: 1600,
    priceMode: "starting_from",
    priceNote: "2x سعر المحامي الأساسي",
    route: "/dashboard/client/requests/new?type=file-lawsuit",
    icon: "Gavel",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "appeal",
    categoryId: "legal-filing",
    label: "مذكرة استئناف",
    description: "تحرير مذكرة استئناف على حكم صادر من محكمة أدنى درجة",
    basePrice: 2000,
    priceMode: "starting_from",
    priceNote: "2x سعر المحامي",
    route: "/dashboard/client/requests/new?type=appeal",
    icon: "Scales",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    tag: "شائع",
    humanService: true,
  },
  {
    serviceId: "cassation",
    categoryId: "legal-filing",
    label: "مذكرة نقض / التماس",
    description: "تحرير مذكرة نقض أمام المحكمة العليا أو التماس إعادة النظر",
    basePrice: 3000,
    priceMode: "starting_from",
    priceNote: "2x سعر المحامي",
    route: "/dashboard/client/requests/new?type=cassation",
    icon: "Scales",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "defense",
    categoryId: "legal-filing",
    label: "مذكرة رد أو دفاع",
    description: "تحرير مذكرة دفاع ردا على ادعاء أو مطالبة قائمة",
    basePrice: 1000,
    priceMode: "starting_from",
    priceNote: "2x سعر المحامي",
    route: "/dashboard/client/requests/new?type=defense",
    icon: "FileText",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "admin-objection",
    categoryId: "legal-filing",
    label: "اعتراض على قرار إداري",
    description: "صياغة مذكرة اعتراض رسمية على قرار جهة حكومية أو تنظيمية",
    basePrice: 800,
    priceMode: "starting_from",
    priceNote: "حسب تعقيد الاعتراض",
    route: "/dashboard/client/requests/new?type=admin-objection",
    icon: "Buildings",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "mediation",
    categoryId: "arbitration",
    label: "جلسة وساطة",
    description: "وسيط معتمد يجمع الطرفين للتوصل إلى تسوية ودية مرضية",
    basePrice: 800,
    priceMode: "starting_from",
    priceNote: "يشمل جلستين + وثيقة التسوية",
    route: "/dashboard/client/requests/new?type=mediation",
    icon: "Users",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    tag: "موصى به",
    humanService: true,
  },
  {
    serviceId: "full-arbitration",
    categoryId: "arbitration",
    label: "تحكيم تجاري كامل",
    description: "تمثيل كامل في إجراءات التحكيم التجاري أمام هيئة التحكيم",
    basePrice: 3000,
    priceMode: "custom",
    priceNote: "حسب تقييم المحكم",
    route: "/dashboard/client/requests/new?type=full-arbitration",
    icon: "Gavel",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "settlement",
    categoryId: "arbitration",
    label: "صياغة اتفاقية تسوية",
    description: "توثيق الاتفاق بين الأطراف في وثيقة قانونية ملزمة",
    basePrice: 399,
    priceMode: "starting_from",
    route: "/dashboard/client/requests/new?type=settlement",
    icon: "CheckCircle",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },

  {
    serviceId: "legal-notice",
    categoryId: "special",
    label: "إنذار قانوني رسمي",
    description: "صياغة وإرسال إنذار رسمي عبر البريد القضائي",
    basePrice: 400,
    priceMode: "starting_from",
    route: "/dashboard/client/requests/new?type=legal-notice",
    icon: "Receipt",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    tag: "الأسرع",
    humanService: true,
  },
  {
    serviceId: "power-of-attorney",
    categoryId: "special",
    label: "توثيق وكالة قانونية",
    description: "إعداد وصياغة الوكالة القانونية + توجيه لإتمام التوثيق",
    basePrice: 600,
    priceMode: "starting_from",
    route: "/dashboard/client/requests/new?type=power-of-attorney",
    icon: "Stamp",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "inheritance",
    categoryId: "special",
    label: "قسمة تركة وحصر الورثة",
    description: "تقييم الحصص القانونية + مساعدة في إجراءات التوثيق القضائي",
    basePrice: 1000,
    priceMode: "starting_from",
    route: "/dashboard/client/requests/new?type=inheritance",
    icon: "Users",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "enforce-judgment",
    categoryId: "special",
    label: "متابعة تنفيذ حكم",
    description: "رفع طلب تنفيذ حكم قضائي صادر + متابعة الإجراءات أمام قلم التنفيذ",
    basePrice: 1200,
    priceMode: "starting_from",
    priceNote: "إجراء تنفيذي - يختلف عن الصياغة",
    route: "/dashboard/client/requests/new?type=enforce-judgment",
    icon: "Gavel",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "translation",
    categoryId: "special",
    label: "ترجمة قانونية معتمدة",
    description: "ترجمة مستنداتك القانونية باعتماد رسمي",
    basePrice: 300,
    priceMode: "per_page",
    priceNote: "يبدأ من 150 ر.س / صفحة",
    route: "/dashboard/client/requests/new?type=translation",
    icon: "Translate",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "public",
    requiresPayment: true,
    humanService: true,
  },
  {
    serviceId: "general",
    categoryId: "special",
    label: "طلب عام",
    description: "طلب قانوني غير مصنف يتم توجيهه حسب نوعه",
    basePrice: 500,
    priceMode: "starting_from",
    route: "/dashboard/client/requests/new?type=general",
    icon: "ShieldStar",
    receiverType: "lawyer",
    requestType: "service",
    betaVisibility: "internal",
    requiresPayment: true,
    humanService: true,
  },
];
