import type { UserSession } from "@/hooks/useUser";
import { getPermissions } from "@/hooks/useUser";

export const DEMO_ACCOUNTS: { key: string; label: string; labelEn: string; color: string; badge?: string; session: UserSession }[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // مقدمو الخدمات (Service Providers)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "lawyer",
    label: "محامي فرد",
    labelEn: "Solo Lawyer",
    color: "from-emerald-700 to-emerald-500",
    badge: "MAX",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "solo",
      name: "أ. فهد العتيبي",
      tier: "max",
      credits: 57,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
    },
  },
  {
    key: "lawyer_bypass",
    label: "محامي فرد — مفتوح",
    labelEn: "Solo Lawyer (Bypass)",
    color: "from-emerald-500 to-teal-400",
    badge: "MAX",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "solo",
      name: "أ. فهد العتيبي (بدون غطاء)",
      tier: "max",
      credits: 57,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
    },
  },
  {
    key: "lawyer_lite",
    label: "محامي — لايت",
    labelEn: "Lawyer Lite",
    color: "from-emerald-600 to-teal-400",
    badge: "FREE",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "trainee",
      name: "أ. محمد الزهراني",
      tier: "free",
      credits: 3,
      creditsMax: 3,
      dashboardMode: "light",
      permissions: getPermissions("lawyer", "free"),
    },
  },
  // ── Law Firm Scenarios ─────────────────────────────────────────────────────
  // سيناريوهات مكاتب المحاماة (4 أحجام: Enterprise / Boutique / Small / Solo+)
  {
    key: "firm",
    label: "مكتب محاماة",
    labelEn: "Law Firm — Boutique (PRO)",
    color: "from-blue-700 to-blue-500",
    badge: "PRO",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: "partner",
      name: "مكتب الشمري للمحاماة",
      tier: "pro",
      credits: 420,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مكتب الشمري للمحاماة", entityType: "firm", role: "managing_partner" },
    },
  },
  {
    key: "firm_enterprise",
    label: "مكتب كبير — إدارات",
    labelEn: "Enterprise Firm — Legal Depts",
    color: "from-blue-900 to-blue-600",
    badge: "Enterprise",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: "partner",
      // مكتب كبير: شركاء متعددون، إدارات (تقاضٍ / تحكيم / عقود)، فروع (الرياض + جدة + الخبر)
      name: "مجموعة الخليج للمحاماة والاستشارات",
      tier: "max",
      credits: 900,
      creditsMax: 1000,
      dashboardMode: "full",
      permissions: getPermissions("firm", "max"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "managing_partner" },
      // يفعّل: الجدران الصينية + لوحة الحوكمة + فروع + CorpMind
    },
  },
  {
    key: "firm_small",
    label: "مكتب صغير — شراكة",
    labelEn: "Small Firm — Partnership",
    color: "from-blue-500 to-indigo-400",
    badge: "Starter",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: "partner",
      // مكتب صغير: 2-3 محامين، تخصص واحد، بدون إدارات رسمية
      name: "مكتب العمر وشركاه للمحاماة",
      tier: "ai",
      credits: 85,
      creditsMax: 200,
      dashboardMode: "full",
      permissions: getPermissions("firm", "ai"),
      affiliation: { entityName: "مكتب العمر وشركاه للمحاماة", entityType: "firm", role: "partner" },
    },
  },
  {
    key: "firm_lawyer",
    label: "محامي داخل مكتب",
    labelEn: "Firm Associate Lawyer",
    color: "from-sky-700 to-cyan-500",
    badge: "محامي",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: null,
      name: "مجموعة الخليج — أ. رامي الحربي",
      tier: "pro",
      credits: 120,
      creditsMax: 300,
      dashboardMode: "full",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "lawyer" },
    },
  },
  {
    key: "firm_secretary",
    label: "سكرتير قانوني",
    labelEn: "Legal Secretary",
    color: "from-slate-600 to-zinc-400",
    badge: "سكرتارية",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: null,
      name: "مجموعة الخليج — هدى الناصر",
      tier: "pro",
      credits: 20,
      creditsMax: 60,
      dashboardMode: "light",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "legal_secretary" },
    },
  },
  {
    key: "firm_finance",
    label: "مالية المكتب",
    labelEn: "Firm Finance Manager",
    color: "from-emerald-700 to-teal-500",
    badge: "مالية",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: null,
      name: "مجموعة الخليج — ماجد السالم",
      tier: "pro",
      credits: 20,
      creditsMax: 80,
      dashboardMode: "full",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "finance_manager" },
    },
  },
  {
    key: "firm_hr",
    label: "موارد بشرية المكتب",
    labelEn: "Firm HR Manager",
    color: "from-fuchsia-700 to-pink-500",
    badge: "HR",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: null,
      name: "مجموعة الخليج — نوف القحطاني",
      tier: "pro",
      credits: 20,
      creditsMax: 80,
      dashboardMode: "full",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "hr_manager" },
    },
  },
  {
    key: "firm_compliance",
    label: "امتثال ومخاطر المكتب",
    labelEn: "Firm Compliance Manager",
    color: "from-teal-700 to-cyan-500",
    badge: "امتثال",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "firm",
      subRole: null,
      name: "مجموعة الخليج — دلال العبدالله",
      tier: "pro",
      credits: 45,
      creditsMax: 120,
      dashboardMode: "full",
      permissions: getPermissions("firm", "pro"),
      affiliation: { entityName: "مجموعة الخليج للمحاماة والاستشارات", entityType: "firm", role: "compliance_manager" },
    },
  },
  {
    key: "notary",
    label: "موثّق رسمي",
    labelEn: "Notary Public",
    color: "from-rose-600 to-pink-400",
    badge: "موثّق",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "provider",
      subRole: "notary",
      name: "الموثّق / محمد العمر",
      tier: "pro",
      credits: 0,
      creditsMax: 0,
      dashboardMode: "full",
      permissions: getPermissions("provider", "pro"),
    },
  },
  {
    key: "gov_reviewer",
    label: "مراجع حكومي",
    labelEn: "Government Reviewer",
    color: "from-sky-700 to-sky-500",
    badge: "معقّب",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "provider",
      subRole: "bailiff",
      name: "المعقّب / سعود المالكي",
      tier: "pro",
      credits: 60,
      creditsMax: 200,
      dashboardMode: "full",
      permissions: getPermissions("provider", "pro"),
      providerSpecialties: ["تعقيب جوازات", "تعقيب بلدية", "تعقيب تجارة", "تعقيب عمل"],
    },
  },
  // ── Multi-Role Combinations ────────────────────────────────────────────────
  {
    key: "lawyer_notary",
    label: "محامي + موثّق",
    labelEn: "Lawyer + Notary",
    color: "from-emerald-600 via-rose-500 to-pink-400",
    badge: "متعدد",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "partner",
      name: "أ. عبدالله الدوسري",
      tier: "max",
      credits: 320,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
      // القاعدة: المحامي عنده صياغة أقوى من الموثق — لكن خدمات التوثيق الرسمي تُضاف
      active_roles: ["notary"],
    },
  },
  {
    key: "lawyer_reviewer",
    label: "محامي + مراجع",
    labelEn: "Lawyer + Reviewer",
    color: "from-emerald-600 via-sky-500 to-blue-400",
    badge: "متعدد",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "solo",
      name: "أ. ناصر القرني",
      tier: "max",
      credits: 410,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
      // المحامي + معقّب: يستطيع قبول طلبات التعقيب في السوق + أدوات المراجعة
      active_roles: ["bailiff"],
    },
  },
  {
    key: "lawyer_all",
    label: "محامي شامل",
    labelEn: "Lawyer — All Roles",
    color: "from-emerald-700 via-sky-600 to-rose-500",
    badge: "شامل",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "partner",
      name: "أ. بدر الحربي",
      tier: "max",
      credits: 480,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
      // كل الأدوار الإضافية: موثق + معقب + محكّم — القاعدة: الأقوى أولاً
      active_roles: ["notary", "bailiff", "arbitrator"],
    },
  },
  {
    key: "lawyer_arbitrator",
    label: "محامي + محكّم",
    labelEn: "Lawyer + Arbitrator",
    color: "from-emerald-600 via-amber-500 to-yellow-400",
    badge: "متعدد",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "lawyer",
      subRole: "partner",
      name: "أ. سالم العتيبي",
      tier: "max",
      credits: 390,
      creditsMax: 600,
      dashboardMode: "full",
      permissions: getPermissions("lawyer", "max"),
      // محامي مرخص للتحكيم: يقبل قضايا التحكيم التجاري والعمالي
      active_roles: ["arbitrator"],
    },
  },
  {
    key: "standalone_arbitrator",
    label: "محكّم تجاري",
    labelEn: "Commercial Arbitrator",
    color: "from-indigo-700 via-purple-600 to-violet-500",
    badge: "محكّم",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "provider",
      subRole: "arbitrator",
      name: "المحكّم / د. خالد الجهني",
      tier: "pro",
      credits: 120,
      creditsMax: 300,
      dashboardMode: "full",
      permissions: getPermissions("provider", "pro"),
      providerSpecialties: ["تحكيم تجاري", "تحكيم عقاري", "تحكيم عمالي", "تحكيم دولي"],
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // طالبو الخدمات — الأفراد
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "individual",
    label: "عميل فرد — AI",
    labelEn: "Individual — AI Plan",
    color: "from-violet-600 to-purple-400",
    badge: "AI",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "individual",
      subRole: null,
      name: "خالد السلمي",
      tier: "ai",
      credits: 12,
      creditsMax: 30,
      dashboardMode: "full",
      permissions: getPermissions("individual", "ai"),
    },
  },
  {
    key: "individual_free",
    label: "عميل فرد — مجاني",
    labelEn: "Individual — Free",
    color: "from-violet-400 to-slate-400",
    badge: "FREE",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "individual",
      subRole: null,
      name: "راشد الحارثي",
      tier: "free",
      credits: 1,
      creditsMax: 1,
      dashboardMode: "light",
      permissions: getPermissions("individual", "free"),
    },
  },
  {
    key: "individual_premium",
    label: "عميل فرد — مميز",
    labelEn: "Individual — Premium",
    color: "from-violet-700 to-indigo-500",
    badge: "PRO",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "individual",
      subRole: null,
      name: "نورة الدوسري",
      tier: "pro",
      credits: 9999,
      creditsMax: 9999,
      dashboardMode: "full",
      permissions: getPermissions("individual", "pro"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // طالبو الخدمات — الشركات (حسب دور الموظف)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "corporate",
    label: "مدير الشركة",
    labelEn: "Company Owner — CORP",
    color: "from-slate-700 to-slate-500",
    badge: "مدير",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: "manager",
      name: "أرامكو — فيصل الزيد",
      tier: "corp",
      credits: 847,
      creditsMax: 1000,
      dashboardMode: "full",
      permissions: getPermissions("corporate", "corp"),
      businessRole: "owner",
    },
  },
  {
    key: "corporate_counsel",
    label: "مستشار قانوني داخلي",
    labelEn: "In-House Legal Counsel",
    color: "from-cyan-700 to-sky-500",
    badge: "مستشار",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: "manager",
      name: "أرامكو — منصور العيسى",
      tier: "corp",
      credits: 763,
      creditsMax: 1000,
      dashboardMode: "full",
      permissions: getPermissions("corporate", "corp"),
      businessRole: "legal_manager",
    },
  },
  {
    key: "corporate_hr",
    label: "مدير الموارد البشرية",
    labelEn: "HR Manager",
    color: "from-rose-600 to-pink-400",
    badge: "HR",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: null,
      name: "أرامكو — سمر الحربي",
      tier: "ai",
      credits: 28,
      creditsMax: 40,
      dashboardMode: "full",
      permissions: getPermissions("corporate", "ai"),
      businessRole: "hr_manager",
    },
  },
  {
    key: "corporate_cfo",
    label: "المدير المالي",
    labelEn: "CFO / Finance Director",
    color: "from-emerald-700 to-teal-400",
    badge: "CFO",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: null,
      name: "أرامكو — طارق الرشيد",
      tier: "ai",
      credits: 19,
      creditsMax: 40,
      dashboardMode: "full",
      permissions: getPermissions("corporate", "ai"),
      businessRole: "finance_manager",
    },
  },
  {
    key: "corporate_employee",
    label: "موظف عادي",
    labelEn: "Regular Employee",
    color: "from-slate-500 to-slate-400",
    badge: "موظف",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: null,
      name: "أرامكو — رنا المالكي",
      tier: "free",
      credits: 1,
      creditsMax: 1,
      dashboardMode: "light",
      permissions: getPermissions("corporate", "free"),
      businessRole: "employee",
    },
  },
  {
    key: "corporate_service",
    label: "شركة — بدون قسم قانوني",
    labelEn: "Company — Service Mode",
    color: "from-amber-600 to-orange-400",
    badge: "خدمة",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: "manager",
      name: "شركة المدار التجارية — نايف العمر",
      tier: "shield",
      credits: 5,
      creditsMax: 10,
      dashboardMode: "light",
      permissions: getPermissions("corporate", "shield"),
      businessRole: "owner",
      businessType: "service",
    },
  },
  {
    key: "corporate_small",
    label: "شركة صغيرة — أساسي",
    labelEn: "Small Company — Starter",
    color: "from-zinc-600 to-slate-400",
    badge: "Starter",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "corporate",
      subRole: "manager",
      name: "مؤسسة الفيحاء — عمر الدوسري",
      tier: "ai",
      credits: 31,
      creditsMax: 40,
      dashboardMode: "full",
      permissions: getPermissions("corporate", "ai"),
      businessRole: "owner",
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // طالبو الخدمات — المنشآت
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "micro",
    label: "منشأة — مجانية",
    labelEn: "Micro Business — Free",
    color: "from-orange-600 to-amber-400",
    badge: "FREE",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "micro",
      subRole: null,
      name: "أبو محمد للبقالة",
      tier: "free",
      credits: 1,
      creditsMax: 1,
      dashboardMode: "light",
      permissions: getPermissions("micro", "free"),
      businessType: "بقالة",
    },
  },
  {
    key: "micro_smart",
    label: "منشأة — ذكية",
    labelEn: "Micro Business — Smart",
    color: "from-orange-700 to-red-500",
    badge: "ذكية",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "micro",
      subRole: null,
      name: "مطعم البيت الكويتي — سعود النفيسي",
      tier: "pro",
      credits: 214,
      creditsMax: 300,
      dashboardMode: "full",
      permissions: getPermissions("micro", "pro"),
      businessType: "مطعم",
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // طالبو الخدمات — الجمعيات
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "ngo",
    label: "جمعية خيرية",
    labelEn: "NGO / Association",
    color: "from-emerald-700 to-teal-500",
    badge: "جمعية",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "ngo",
      subRole: null,
      name: "جمعية الرعاية الاجتماعية",
      tier: "pro",
      credits: 127,
      creditsMax: 300,
      dashboardMode: "full",
      permissions: getPermissions("ngo", "pro"),
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // جهات حكومية (Government)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "government_judge",
    label: "قاضي",
    labelEn: "Judge",
    color: "from-amber-700 to-yellow-500",
    badge: "حكومي",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "government",
      subRole: null,
      name: "القاضي / سلطان العنزي",
      tier: "pro",
      credits: 200,
      creditsMax: 500,
      dashboardMode: "full",
      permissions: getPermissions("government", "pro"),
      governmentRole: "judge",
    },
  },
  {
    key: "government_prosecutor",
    label: "عضو نيابة عامة",
    labelEn: "Prosecutor",
    color: "from-red-700 to-rose-500",
    badge: "نيابة",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "government",
      subRole: null,
      name: "المدعي العام / خالد الشمري",
      tier: "pro",
      credits: 180,
      creditsMax: 500,
      dashboardMode: "full",
      permissions: getPermissions("government", "pro"),
      governmentRole: "prosecutor",
    },
  },
  {
    key: "government_officer",
    label: "ضابط — مباحث",
    labelEn: "Detective Officer",
    color: "from-slate-600 to-slate-400",
    badge: "ضابط",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "government",
      subRole: null,
      name: "الرائد / فيصل الغامدي",
      tier: "pro",
      credits: 150,
      creditsMax: 500,
      dashboardMode: "full",
      permissions: getPermissions("government", "pro"),
      governmentRole: "officer",
      officerSpecialty: "detective",
    },
  },
  {
    key: "government_counsel",
    label: "مستشار حكومي",
    labelEn: "Gov Counsel",
    color: "from-blue-700 to-sky-500",
    badge: "مستشار",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "government",
      subRole: null,
      name: "المستشار / عبدالله القحطاني",
      tier: "pro",
      credits: 250,
      creditsMax: 500,
      dashboardMode: "full",
      permissions: getPermissions("government", "pro"),
      governmentRole: "gov_counsel",
    },
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // أدوار أخرى (Other Roles)
  // ═══════════════════════════════════════════════════════════════════════════
  {
    key: "admin",
    label: "مدير النظام",
    labelEn: "Admin",
    color: "from-red-700 to-red-500",
    badge: "ADMIN",
    session: {
      isLoggedIn: true,
      country: "SA",
      userType: "admin",
      subRole: "partner",
      name: "Admin — نظامي",
      tier: "max",
      credits: 9999,
      creditsMax: 9999,
      dashboardMode: "full",
      permissions: getPermissions("admin", "max"),
    },
  },
  {
    key: "guest",
    label: "زائر (غير مسجّل)",
    labelEn: "Guest",
    color: "from-zinc-600 to-zinc-400",
    session: {
      isLoggedIn: false,
      country: "SA",
      userType: null,
      subRole: null,
      name: "",
      tier: "free",
      credits: 0,
      creditsMax: 0,
      dashboardMode: "light",
      permissions: [],
    },
  },
];
