import type {
  FirmAdminControl,
  FirmPlanContract,
  FirmPracticeModel,
  FirmProfileScenario,
  FirmRole,
  FirmRoleContract,
  FirmServiceEntitlement,
  FirmServiceKey,
  FirmSize,
  FirmStructure,
} from "@/types/firmBackendReady";

export const FIRM_SIZE_LABEL: Record<FirmSize, string> = {
  solo_office: "مكتب شريك واحد",
  small_firm: "مكتب صغير",
  mid_firm: "شركة محاماة متوسطة",
  large_firm: "شركة محاماة كبيرة",
  enterprise_firm: "شبكة/شركة محاماة Enterprise",
};

export const FIRM_STRUCTURE_LABEL: Record<FirmStructure, string> = {
  single_partner: "شريك مدير واحد",
  partners: "شركاء وفريق",
  practice_departments: "أقسام ممارسة قانونية",
  multi_branch: "فروع متعددة",
  network_hybrid: "شبكة هجينة مع مستشارين خارجيين",
};

export const FIRM_PRACTICE_MODEL_LABEL: Record<FirmPracticeModel, string> = {
  litigation: "تقاض وقضايا",
  full_service: "خدمات قانونية شاملة",
  boutique: "تخصص دقيق",
  corporate_advisory: "شركات وعقود وصفقات",
  mixed: "مزيج تقاض واستشارات",
};

export const FIRM_ROLE_LABEL: Record<FirmRole, string> = {
  managing_partner: "الشريك المدير",
  partner: "شريك",
  senior_lawyer: "محام أول",
  lawyer: "محام",
  trainee: "متدرب",
  legal_secretary: "سكرتير قانوني",
  office_admin: "مدير مكتب",
  finance_manager: "مدير مالي",
  hr_manager: "مدير موارد بشرية",
  compliance_manager: "مدير امتثال ومخاطر",
  external_of_counsel: "مستشار خارجي Of Counsel",
  legal_consultant: "مستشار قانوني",
  in_house_counsel: "مستشار قانوني داخلي",
};

export const FIRM_PLAN_CONTRACTS: FirmPlanContract[] = [
  {
    plan: "firm-basic",
    annualPrice: 17988,
    includedSeats: 3,
    extraSeatAnnualPrice: 2388,
    includedAnnualPoints: 30000,
    maxSeats: 8,
    betaLocked: true,
  },
  {
    plan: "firm-growth",
    annualPrice: 47988,
    includedSeats: 10,
    extraSeatAnnualPrice: 2988,
    includedAnnualPoints: 120000,
    maxSeats: 30,
    betaLocked: true,
  },
  {
    plan: "firm-scale",
    annualPrice: 95988,
    includedSeats: 25,
    extraSeatAnnualPrice: 3588,
    includedAnnualPoints: 360000,
    maxSeats: 75,
    betaLocked: true,
  },
  {
    plan: "firm-enterprise",
    annualPrice: 179988,
    includedSeats: 50,
    extraSeatAnnualPrice: null,
    includedAnnualPoints: 900000,
    maxSeats: null,
    betaLocked: true,
  },
];

export const FIRM_ROLE_CONTRACTS: FirmRoleContract[] = [
  {
    role: "managing_partner",
    label: "الشريك المدير",
    scopes: ["firm", "finance", "points", "settings", "audit"],
    permissions: ["*"],
    canViewFirmWallet: true,
    canViewDepartmentWallet: true,
    canRequestTopUp: true,
  },
  {
    role: "partner",
    label: "شريك",
    scopes: ["firm", "department", "points", "audit"],
    permissions: ["cases:*", "clients:*", "team:assign", "reports:view", "wallet:view"],
    canViewFirmWallet: true,
    canViewDepartmentWallet: true,
    canRequestTopUp: true,
  },
  {
    role: "senior_lawyer",
    label: "محام أول",
    scopes: ["department", "assigned_cases", "points"],
    permissions: ["cases:view", "cases:edit", "cases:assign", "clients:view", "docs:*", "ai:*"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: true,
    canRequestTopUp: true,
  },
  {
    role: "lawyer",
    label: "محام",
    scopes: ["assigned_cases", "own_work"],
    permissions: ["cases:view", "cases:edit", "clients:view", "docs:upload", "ai:use"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: true,
  },
  {
    role: "trainee",
    label: "متدرب",
    scopes: ["assigned_cases", "own_work"],
    permissions: ["cases:view", "docs:view", "ai:limited"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
  {
    role: "legal_secretary",
    label: "سكرتير قانوني",
    scopes: ["assigned_cases", "own_work"],
    permissions: ["calendar:*", "docs:upload", "clients:view", "cases:view"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
  {
    role: "office_admin",
    label: "مدير مكتب",
    scopes: ["firm", "settings"],
    permissions: ["team:view", "team:invite", "settings:view", "calendar:*"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: true,
  },
  {
    role: "finance_manager",
    label: "مدير مالي",
    scopes: ["finance", "points", "audit"],
    permissions: ["finance:*", "wallet:*", "billing:*", "reports:finance"],
    canViewFirmWallet: true,
    canViewDepartmentWallet: true,
    canRequestTopUp: true,
  },
  {
    role: "hr_manager",
    label: "مدير موارد بشرية",
    scopes: ["firm", "settings"],
    permissions: ["team:view", "attendance:*", "trainees:*", "hr:*"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
  {
    role: "compliance_manager",
    label: "مدير امتثال ومخاطر",
    scopes: ["firm", "audit"],
    permissions: ["conflict:*", "kyc:*", "chinese_walls:*", "audit:view"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: true,
    canRequestTopUp: true,
  },
  {
    role: "external_of_counsel",
    label: "مستشار خارجي Of Counsel",
    scopes: ["assigned_cases"],
    permissions: ["cases:view", "docs:view", "shared_rooms:comment"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
  {
    role: "legal_consultant",
    label: "مستشار قانوني",
    scopes: ["assigned_cases", "own_work", "settings"],
    permissions: ["cases:view", "clients:view", "docs:*", "ai:*"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
  {
    role: "in_house_counsel",
    label: "مستشار قانوني داخلي",
    scopes: ["assigned_cases", "own_work", "settings"],
    permissions: ["cases:view", "clients:view", "docs:*", "ai:*"],
    canViewFirmWallet: false,
    canViewDepartmentWallet: false,
    canRequestTopUp: false,
  },
];

export const FIRM_SERVICE_ENTITLEMENTS: FirmServiceEntitlement[] = [
  {
    key: "core_cases",
    label: "القضايا والعملاء والمستندات",
    description: "تشغيل المكتب الأساسي: قضايا، عملاء، مهام، جلسات، ومستندات.",
    availableForSizes: ["solo_office", "small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    routes: ["/dashboard/firm/cases", "/dashboard/firm/clients", "/dashboard/firm/documents"],
    contract: "FirmProfileContract",
    readiness: "UI Working",
  },
  {
    key: "firm_points_wallet",
    label: "محفظة نقاط الشركة",
    description: "رصيد نقاط سنوي للشركة مع توزيع على الأقسام والموظفين حسب الصلاحيات.",
    availableForSizes: ["solo_office", "small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    routes: ["/dashboard/firm/wallet", "/dashboard/admin/provider-verification/firms"],
    contract: "FirmPointsWallet",
    readiness: "Backend-ready",
  },
  {
    key: "practice_departments",
    label: "أقسام ممارسة قانونية",
    description: "تقاض، عقود، شركات، عمال، عقار، تحكيم، تنفيذ، أبحاث، امتثال، وملكية فكرية.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/departments"],
    contract: "FirmOrgUnit",
    readiness: "Backend-ready",
  },
  {
    key: "branches",
    label: "فروع المكتب",
    description: "ربط الفرق والملفات والميزانيات بفروع مختلفة داخل نفس شركة المحاماة.",
    availableForSizes: ["large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/branches"],
    contract: "FirmBranch",
    readiness: "Backend-ready",
  },
  {
    key: "finance",
    label: "مالية وفوترة",
    description: "إيرادات، أتعاب، فواتير، مصروفات، ورؤية نقاط واستهلاك الشركة.",
    availableForSizes: ["small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/finance", "/dashboard/firm/fees"],
    contract: "FirmFinancialReport",
    readiness: "Backend-ready",
  },
  {
    key: "hr",
    label: "HR وتدريب",
    description: "حضور، إجازات، متدربون، وسعة عمل المحامين داخل الشركة.",
    availableForSizes: ["small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/team/attendance", "/dashboard/firm/team/trainees"],
    contract: "FirmHrProgram",
    readiness: "UI Working",
  },
  {
    key: "governance",
    label: "حوكمة وامتثال",
    description: "مصفوفة صلاحيات، سجل تدقيق، اعتماد داخلي، وسياسات إدارة المخاطر.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/governance"],
    contract: "FirmGovernanceProgram",
    readiness: "Backend-ready",
  },
  {
    key: "chinese_walls",
    label: "Chinese Walls",
    description: "عزل فرق وملفات عند تعارض المصالح أو حساسية العميل.",
    availableForSizes: ["large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/compliance/walls"],
    contract: "FirmConflictWall",
    readiness: "Backend-ready",
  },
  {
    key: "client_portal",
    label: "بوابة العملاء",
    description: "مساحة عميل لعرض المستندات والتحديثات والطلبات بحدود صلاحيات واضحة.",
    availableForSizes: ["small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/client-portal", "/dashboard/firm/branding"],
    contract: "FirmClientPortal",
    readiness: "UI Working",
  },
  {
    key: "external_collaboration",
    label: "تعاون خارجي",
    description: "Of Counsel، غرف مشتركة، وإسناد عمل مؤقت دون خلط صلاحيات المكتب.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/of-counsel", "/dashboard/firm/shared-rooms"],
    contract: "FirmExternalCollaboration",
    readiness: "Backend-ready",
  },
  {
    key: "marketplace",
    label: "سوق المهنيين",
    description: "نشر طلبات تعاون أو تصفح فرص السوق باسم شركة المحاماة.",
    availableForSizes: ["small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/marketplace", "/marketplace"],
    contract: "FirmMarketplaceAccess",
    readiness: "Backend-ready",
  },
  {
    key: "secondment",
    label: "إعارات محامين",
    description: "إتاحة عرض أو استقبال محام منتدب مع حدود صلاحيات واضحة.",
    availableForSizes: ["large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/secondment/new"],
    contract: "FirmSecondmentOffer",
    readiness: "Backend-ready",
  },
  {
    key: "shared_rooms",
    label: "غرف مشتركة",
    description: "مساحات تعاون مؤقتة مع شركات أو مستشارين خارجيين دون فتح كل بيانات المكتب.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/shared-rooms"],
    contract: "FirmSharedRoom",
    readiness: "UI Working",
  },
  {
    key: "advanced_ai",
    label: "AI متقدم بنقاط الشركة",
    description: "تحليل مستندات ضخمة، OCR، ترجمة، مراجعة عقود، وتلخيص ملفات حسب رصيد النقاط.",
    availableForSizes: ["small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/ai/analyze?source=firm", "/ai/legal-translate", "/ai/contract-reviewer"],
    contract: "FirmAiUsageEntitlement",
    readiness: "Backend-ready",
  },
  {
    key: "legal_library",
    label: "المكتبة القانونية",
    description: "وصول للمكتبة القانونية مع توثيق مصادر واعتماد نشر لاحقاً.",
    availableForSizes: ["solo_office", "small_firm", "mid_firm", "large_firm", "enterprise_firm"],
    routes: ["/laws"],
    contract: "LegalLibrarySystem",
    readiness: "Backend-ready",
  },
  {
    key: "analytics",
    label: "تحليلات وتقارير",
    description: "تقارير أداء الفريق، القضايا، المالية، والنقاط حسب الدور.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/analytics", "/dashboard/firm/finance/reports"],
    contract: "FirmAnalyticsReport",
    readiness: "Backend-ready",
  },
  {
    key: "health_check",
    label: "Health Check 360",
    description: "فحص جاهزية المكتب: الحوكمة، تضارب المصالح، النقاط، الأقسام، والتشغيل.",
    availableForSizes: ["mid_firm", "large_firm", "enterprise_firm"],
    needsAdminFlag: true,
    routes: ["/dashboard/firm/health-check"],
    contract: "FirmHealthCheck",
    readiness: "Backend-ready",
  },
];

export const FIRM_PROFILE_SCENARIOS: FirmProfileScenario[] = [
  {
    id: "solo-office-basic",
    title: "مكتب شريك واحد",
    firmSize: "solo_office",
    structure: "single_partner",
    practiceModel: "boutique",
    description: "مكتب صغير يحتاج تشغيل قضايا وعملاء ومستندات ومحفظة نقاط واحدة بدون تعقيد إدارات.",
    roles: ["managing_partner", "lawyer", "legal_secretary"],
    recommendedServices: ["core_cases", "firm_points_wallet", "client_portal", "legal_library"],
    dashboardRoutes: ["/dashboard/firm", "/dashboard/firm/cases", "/dashboard/firm/wallet"],
    adminRoute: "/dashboard/admin/provider-verification/firms",
    readiness: "Backend-ready",
    backendBoundary: "الاشتراك والنقاط والمقاعد محلية فقط حتى ربط FirmProfile/Billing/Wallet APIs.",
    betaNotes: "النقاط توقف الخدمات الاستهلاكية فقط ولا توقف تشغيل القضايا والعملاء.",
  },
  {
    id: "small-partners-growth",
    title: "مكتب شركاء وفريق صغير",
    firmSize: "small_firm",
    structure: "partners",
    practiceModel: "mixed",
    description: "فريق شركاء ومحامين يحتاج إدارة فريق، بوابة عملاء، مالية أساسية، ونقاط مشتركة للشركة.",
    roles: ["managing_partner", "partner", "senior_lawyer", "lawyer", "trainee", "legal_secretary", "office_admin", "finance_manager"],
    recommendedServices: ["core_cases", "firm_points_wallet", "client_portal", "finance", "advanced_ai", "legal_library"],
    dashboardRoutes: ["/dashboard/firm/team", "/dashboard/firm/finance", "/dashboard/firm/client-portal"],
    adminRoute: "/dashboard/admin/provider-verification/firms",
    readiness: "Backend-ready",
    backendBoundary: "إضافة الأعضاء وتغيير الباقة محليان فقط، والدعوات الحقيقية تنتظر Auth/RBAC backend.",
    betaNotes: "تظل رسائل Backend-ready ظاهرة عند إضافة عضو أو تعديل رصيد نقاط.",
  },
  {
    id: "mid-practice-departments",
    title: "شركة متوسطة بأقسام ممارسة",
    firmSize: "mid_firm",
    structure: "practice_departments",
    practiceModel: "full_service",
    description: "أقسام تقاض وعقود وشركات وامتثال مع مديري أقسام ورؤية منفصلة لصرف النقاط.",
    roles: ["managing_partner", "partner", "senior_lawyer", "lawyer", "trainee", "legal_secretary", "office_admin", "finance_manager", "hr_manager", "compliance_manager", "legal_consultant", "in_house_counsel"],
    recommendedServices: ["core_cases", "firm_points_wallet", "practice_departments", "finance", "governance", "client_portal", "external_collaboration", "advanced_ai", "health_check"],
    dashboardRoutes: ["/dashboard/firm/departments", "/dashboard/firm/governance", "/dashboard/firm/health-check"],
    adminRoute: "/dashboard/admin/provider-verification/firms",
    readiness: "Backend-ready",
    backendBoundary: "تقسيم النقاط على الأقسام UI-ready فقط، ومصدر الحقيقة ينتظر Wallet/RBAC APIs.",
    betaNotes: "مدير القسم يرى قسمه فقط، والشريك المدير يرى الشركة كلها.",
  },
  {
    id: "large-multi-branch-scale",
    title: "شركة كبيرة بفروع وحوكمة",
    firmSize: "large_firm",
    structure: "multi_branch",
    practiceModel: "full_service",
    description: "شركة متعددة الفرق والفروع تحتاج حوكمة، Chinese Walls، غرف مشتركة، وتحليلات على مستوى الشركة.",
    roles: ["managing_partner", "partner", "senior_lawyer", "lawyer", "trainee", "legal_secretary", "office_admin", "finance_manager", "hr_manager", "compliance_manager", "external_of_counsel", "legal_consultant", "in_house_counsel"],
    recommendedServices: ["core_cases", "firm_points_wallet", "practice_departments", "branches", "finance", "hr", "governance", "chinese_walls", "marketplace", "external_collaboration", "shared_rooms", "advanced_ai", "analytics", "health_check"],
    dashboardRoutes: ["/dashboard/firm/compliance/walls", "/dashboard/firm/shared-rooms", "/dashboard/firm/analytics"],
    adminRoute: "/dashboard/admin/provider-verification/firms",
    readiness: "Backend-ready",
    backendBoundary: "Chinese Walls وسجل التدقيق واجهة فقط ولا تعزل بيانات حقيقية حتى backend.",
    betaNotes: "لا إزالة لتحذيرات البيتا قبل وجود audit log وpolicy enforcement فعلي.",
  },
  {
    id: "enterprise-network",
    title: "شبكة/شركة محاماة Enterprise",
    firmSize: "enterprise_firm",
    structure: "network_hybrid",
    practiceModel: "mixed",
    description: "شبكة فروع وممارسات وشركاء خارجيين تحتاج إعدادات مخصصة ونقاط ضخمة وعقد سنوي.",
    roles: ["managing_partner", "partner", "senior_lawyer", "lawyer", "trainee", "legal_secretary", "office_admin", "finance_manager", "hr_manager", "compliance_manager", "external_of_counsel", "legal_consultant", "in_house_counsel"],
    recommendedServices: ["core_cases", "firm_points_wallet", "practice_departments", "branches", "finance", "hr", "governance", "chinese_walls", "marketplace", "external_collaboration", "secondment", "shared_rooms", "advanced_ai", "legal_library", "analytics", "health_check"],
    dashboardRoutes: ["/dashboard/firm", "/dashboard/firm/governance", "/dashboard/admin/provider-verification/firms"],
    adminRoute: "/dashboard/admin/provider-verification/firms",
    readiness: "Backend-ready",
    backendBoundary: "Enterprise لا يعمل إنتاجيا قبل SSO/Billing/SLA/Audit APIs.",
    betaNotes: "يظل السعر مخصصا وbetaLocked حتى اعتماد نموذج العقود السنوية.",
  },
];

export const FIRM_ADMIN_CONTROLS: FirmAdminControl[] = [
  {
    id: "firm-provider-profile",
    title: "اعتماد بروفيل شركة المحاماة",
    route: "/dashboard/admin/provider-verification/firms",
    contract: "FirmProfileContract",
    readiness: "Backend-ready",
    note: "إدارة الحجم والهيكل والأقسام والتخصص داخل المزودين، بدون حفظ خادمي.",
  },
  {
    id: "firm-annual-plan",
    title: "اشتراك سنوي + مقاعد + نقاط",
    route: "/dashboard/admin/pricing",
    contract: "FirmPlanContract",
    readiness: "Backend-ready",
    note: "النموذج السنوي يظهر في التسعير، والاحتساب الحقيقي ينتظر Billing API.",
  },
  {
    id: "firm-wallet",
    title: "محفظة نقاط الشركة والأقسام",
    route: "/dashboard/admin/provider-verification/firms",
    contract: "FirmPointsWallet",
    readiness: "Backend-ready",
    note: "نفاد النقاط يوقف الخدمات الاستهلاكية فقط، لا القضايا والعملاء والتشغيل الأساسي.",
  },
  {
    id: "firm-rbac",
    title: "أدوار وصلاحيات شركة المحاماة",
    route: "/dashboard/firm/team/roles",
    contract: "FirmRoleContract",
    readiness: "Backend-ready",
    note: "المصفوفة UI-ready، والإلزام الحقيقي ينتظر Auth/RBAC backend.",
  },
  {
    id: "firm-audit",
    title: "سجل تدقيق تعديلات firm",
    route: "/dashboard/admin/audit-log",
    contract: "FirmAuditEvent",
    readiness: "Risk",
    note: "أي تعديل محلي يحتاج لاحقا before/after وactor/time/entity قبل الإنتاج.",
  },
];

export function resolveFirmScenario(
  firmSize: FirmSize,
  structure: FirmStructure,
  practiceModel: FirmPracticeModel,
): FirmProfileScenario {
  return (
    FIRM_PROFILE_SCENARIOS.find((scenario) =>
      scenario.firmSize === firmSize &&
      scenario.structure === structure &&
      scenario.practiceModel === practiceModel
    ) ??
    FIRM_PROFILE_SCENARIOS.find((scenario) => scenario.firmSize === firmSize) ??
    FIRM_PROFILE_SCENARIOS[0]
  );
}

export function firmServiceKeyToFeatureFlag(serviceKey: FirmServiceKey) {
  const map: Partial<Record<FirmServiceKey, string>> = {
    practice_departments: "hasDepartments",
    branches: "hasBranches",
    finance: "hasFinance",
    hr: "hasHr",
    governance: "hasGovernance",
    chinese_walls: "hasChineseWalls",
    client_portal: "hasClientPortal",
    marketplace: "hasMarketplace",
    external_collaboration: "hasExternalCollaboration",
    secondment: "hasSecondment",
    shared_rooms: "hasSharedRooms",
    advanced_ai: "hasAdvancedAi",
    legal_library: "hasLegalLibrary",
    analytics: "hasAnalytics",
    health_check: "hasHealthCheck",
    firm_points_wallet: "hasFirmPointsWallet",
  };

  return map[serviceKey];
}
