import {
  ChatCircleDots, Scales, FileText, Stamp, Shield, Brain
} from "@phosphor-icons/react";

export const services = {
  ar: [
    {
      id: "consultation",
      icon: ChatCircleDots,
      label: "استشارة قانونية",
      tagline: "احصل على إجابة قانونية فورية",
      desc: "استشارة مباشرة مع محامي معتمد — صوتية أو مرئية أو حضورية — أو عبر نظامي AI المتخصص في الأنظمة السعودية.",
      href: "/services/consultations",
      price: "٩٩ ر.س",
      duration: "٣٠ دقيقة",
      color: "bg-royal/5 text-royal",
      borderHover: "hover:border-royal/20",
      features: ["استشارة فورية بدون انتظار", "محامون معتمدون من وزارة العدل", "تقرير مكتوب بعد الاستشارة", "نظامي AI متاح ٢٤/٧"],
    },
    {
      id: "litigation",
      icon: Scales,
      label: "تمثيل قضائي",
      tagline: "محامٍ يترافع عنك في المحكمة",
      desc: "وكّل محامياً متخصصاً يترافع نيابةً عنك في جميع درجات التقاضي — ابتدائي، استئناف، وعليا.",
      href: "/services/legal-representation",
      price: "يُحدد بعد التقييم",
      duration: "حسب القضية",
      color: "bg-gold/10 text-gold-dark",
      borderHover: "hover:border-gold/20",
      features: ["محامون متخصصون في كل نوع قضايا", "متابعة مستمرة للقضية", "تقارير دورية للموكّل", "نظام Escrow لحماية الأتعاب"],
    },
    {
      id: "contracts",
      icon: FileText,
      label: "عقود",
      tagline: "صياغة ومراجعة احترافية",
      desc: "صياغة عقد جديد أو مراجعة عقد موجود بمساعدة AI تكشف البنود المجحفة، يراجعها محامٍ متخصص.",
      href: "/services/contracts",
      price: "٢٤٩ ر.س",
      duration: "٢٤ ساعة",
      color: "bg-emerald-50 text-emerald-600",
      borderHover: "hover:border-emerald-200",
      features: ["AI يكشف البنود المجحفة تلقائياً", "مراجعة محامٍ متخصص", "تعديلات غير محدودة", "نموذج مخصص لاحتياجك"],
    },
    {
      id: "notary",
      icon: Stamp,
      label: "توثيق رسمي",
      tagline: "توثيق سريع وموثوق",
      desc: "توثيق العقود والمحررات الرسمية عبر موثقين معتمدين — إلكترونياً أو حضورياً.",
      href: "/services/notary",
      price: "١٩٩ ر.س",
      duration: "٤٨ ساعة",
      color: "bg-blue-50 text-blue-600",
      borderHover: "hover:border-blue-200",
      features: ["موثقون معتمدون رسمياً", "توثيق إلكتروني معترف به", "حفظ رقمي آمن للوثائق", "إشعارات وتذكيرات التجديد"],
    },
    {
      id: "tracking",
      icon: Shield,
      label: "مراجعة الدوائر الحكومية",
      tagline: "أنجز معاملاتك الحكومية",
      desc: "إنجاز المعاملات الحكومية والقانونية نيابةً عنك — تراخيص، سجلات، وزارات.",
      href: "/services/tracking",
      price: "١٤٩ ر.س",
      duration: "يوم عمل",
      color: "bg-orange-50 text-orange-600",
      borderHover: "hover:border-orange-200",
      features: ["معقّبون معتمدون لدى الجهات الرسمية", "متابعة لحظية للمعاملة", "إشعار فوري عند الانتهاء", "ضمان استرداد في حال التأخير"],
      badge: null,
    },
    {
      id: "case-study",
      icon: Brain,
      label: "دراسة وتقييم القضايا",
      tagline: "اعرف موقفك القانوني قبل أن تتحرك",
      desc: "جلسة تقييم متعمقة مع محامٍ متخصص يدرس ملف قضيتك ويُقدّر فرص النجاح والمخاطر قبل أي خطوة قانونية.",
      href: "/services/individuals/case-study",
      price: "يبدأ من ٤٩٩ ر.س",
      duration: "٢-٥ أيام",
      color: "bg-royal/5 text-royal",
      borderHover: "hover:border-royal/20",
      features: ["تحليل وثائق القضية بـ AI", "تقييم فرص النجاح بنسبة مئوية", "توصية باستراتيجية قانونية", "يُخصم من أتعاب التمثيل عند التوكيل"],
      badge: "جديد",
    },
  ],
  en: [
    {
      id: "consultation",
      icon: ChatCircleDots,
      label: "Legal Consultation",
      tagline: "Get an instant legal answer",
      desc: "Direct consultation with a certified lawyer — voice, video, in-person, or via Nezamy AI trained on Saudi law.",
      href: "/services/consultations",
      price: "99 SAR",
      duration: "30 minutes",
      color: "bg-royal/5 text-royal",
      borderHover: "hover:border-royal/20",
      features: ["Instant consultation, no wait", "Ministry of Justice certified lawyers", "Written report after session", "Nezamy AI available 24/7"],
    },
    {
      id: "litigation",
      icon: Scales,
      label: "Court Representation",
      tagline: "A lawyer who argues for you",
      desc: "Appoint a specialized lawyer to represent you at all court levels — first instance, appeal, and supreme.",
      href: "/services/legal-representation",
      price: "Determined after assessment",
      duration: "Case-dependent",
      color: "bg-gold/10 text-gold-dark",
      borderHover: "hover:border-gold/20",
      features: ["Specialists for each case type", "Continuous case follow-up", "Periodic client reports", "Escrow system for fee protection"],
    },
    {
      id: "contracts",
      icon: FileText,
      label: "Contracts",
      tagline: "Professional drafting & review",
      desc: "Draft a new contract or review an existing one with AI flagging unfair clauses, reviewed by a specialist lawyer.",
      href: "/services/contracts",
      price: "249 SAR",
      duration: "24 hours",
      color: "bg-emerald-50 text-emerald-600",
      borderHover: "hover:border-emerald-200",
      features: ["AI auto-detects unfair clauses", "Human review by specialist lawyer", "Unlimited revisions", "Custom template for your needs"],
    },
    {
      id: "notary",
      icon: Stamp,
      label: "Notarization",
      tagline: "Fast and reliable notarization",
      desc: "Official document notarization via certified notaries — digitally or in person.",
      href: "/services/notary",
      price: "199 SAR",
      duration: "48 hours",
      color: "bg-blue-50 text-blue-600",
      borderHover: "hover:border-blue-200",
      features: ["Officially certified notaries", "Legally recognized e-notarization", "Secure digital document storage", "Renewal reminders & notifications"],
    },
    {
      id: "tracking",
      icon: Shield,
      label: "Gov. Follow-up",
      tagline: "Get your government transactions done",
      desc: "Complete government and legal transactions on your behalf — licenses, registrations, ministries.",
      href: "/services/tracking",
      price: "149 SAR",
      duration: "1 business day",
      color: "bg-orange-50 text-orange-600",
      borderHover: "hover:border-orange-200",
      features: ["Agents accredited with official bodies", "Real-time transaction tracking", "Instant completion notification", "Refund guarantee for delays"],
      badge: null,
    },
    {
      id: "case-study",
      icon: Brain,
      label: "Case Study & Assessment",
      tagline: "Know your legal position before you act",
      desc: "An in-depth assessment session with a specialist lawyer who studies your case file and estimates success odds and risks before any legal step.",
      href: "/services/individuals/case-study",
      price: "Starting from 499 SAR",
      duration: "2–5 days",
      color: "bg-royal/5 text-royal",
      borderHover: "hover:border-royal/20",
      features: ["AI-powered case document analysis", "Success probability estimation", "Legal strategy recommendation", "Deducted from representation fees upon power of attorney"],
      badge: "New",
    },
  ],
};

export const faqs = {
  ar: [
    { q: "هل الاستشارة سرية تماماً؟", a: "نعم. كل استشارة محمية بسرية مهنية كاملة وفق نظام المحاماة السعودي." },
    { q: "كيف يعمل نظام الضمان المالي؟", a: "نستخدم نظام Escrow — مبلغ الأتعاب محتجز لديك حتى تؤكد اكتمال الخدمة." },
    { q: "هل يمكنني تقييم المحامي بعد الانتهاء؟", a: "بالتأكيد. نظام التقييم شفاف ومرئي للجميع لضمان جودة الخدمة." },
    { q: "ماذا إذا لم أكن راضياً عن الخدمة؟", a: "لدينا سياسة استرداد كاملة خلال ٧٢ ساعة إذا لم تكن الخدمة مطابقة للمواصفات." },
  ],
  en: [
    { q: "Is the consultation fully confidential?", a: "Yes. Every consultation is protected by full professional confidentiality under Saudi Bar regulations." },
    { q: "How does the financial guarantee work?", a: "We use an Escrow system — fees are held until you confirm service completion." },
    { q: "Can I rate the lawyer after the service?", a: "Absolutely. Our rating system is transparent and public to ensure service quality." },
    { q: "What if I'm not satisfied with the service?", a: "We offer a full refund within 72 hours if the service doesn't meet specifications." },
  ],
};
