-- ============================================================
-- Migration: 20260826_receipts.sql
-- Owner ruling of 26 August, row ١٥ — «سندات القبض المالية … اعتماد المسار
-- المزدوج (توليد PDF آلي + رفع يدوي مساعد)».
--
-- WHAT THIS IS FOR
-- ----------------
-- There is no payment provider connected to this platform. Every riyal the
-- office has actually received arrived by bank transfer, cash or cheque, and
-- was acknowledged on paper or not at all. This table is the ledger of those
-- acknowledgements: one row per receipt the office issues, with a running
-- serial a client can quote.
--
-- THE SERIAL IS GENERATED BY THE DATABASE, ON PURPOSE
-- ---------------------------------------------------
-- A receipt serial must be unique across every receipt ever issued. Computing
-- it in the app means reading the highest one and adding one, and two admins
-- pressing «إصدار سند» in the same second then hand two clients the same
-- number — with nothing afterwards able to say which is which.
--
-- `serial` is therefore a STORED GENERATED column over this table's own
-- bigserial. Uniqueness comes from the sequence itself, so there is no read,
-- no race, and no way for the application to get it wrong. The expression uses
-- only immutable functions (lpad, ||, ::text) as a generated column requires —
-- which is why the year is its own integer column rather than to_char() over a
-- timestamp, since to_char(timestamptz, text) is STABLE, not IMMUTABLE, and
-- Postgres rejects it here.
--
-- ADDITIVE ONLY
-- -------------
-- One new table, one index, four policies. No existing table is altered, no
-- column is dropped, nothing is backfilled or deleted. Safe to run on a live
-- database, and safe to run twice.
-- ============================================================

create table if not exists public.receipts (
  id            bigserial primary key,

  -- The order this acknowledges. `on delete set null` rather than cascade: a
  -- receipt is a financial record and must outlive the order it refers to —
  -- deleting an order must never make the money that was received disappear.
  request_id    text references public.service_requests(id) on delete set null,

  -- Year of issue, kept as its own column so the generated `serial` below can
  -- be immutable. Defaulted from the server clock at insert.
  issue_year    integer not null default extract(year from now())::integer,

  -- REC-2026-00042. Generated, never written by the application.
  serial        text generated always as
                  ('REC-' || issue_year::text || '-' || lpad(id::text, 5, '0')) stored,

  amount        numeric(12,2) not null check (amount >= 0),
  currency      text not null default 'SAR',

  -- The amount in Arabic words, as printed. STORED rather than recomputed on
  -- read: a receipt is a record of what was handed over, and if the wording
  -- helper is ever corrected, previously issued receipts must keep saying what
  -- they said. See src/lib/services/tafqit.ts.
  amount_words  text not null,

  payer_name    text,

  -- How the money arrived. Closed list, mirrored by RECEIPT_METHODS in
  -- src/lib/services/receiptSerial.ts. No card or online method appears here:
  -- no provider is connected, so such a receipt would describe something that
  -- cannot have happened.
  method        text not null check (method in ('bank_transfer', 'cash', 'cheque', 'other')),

  -- The bank/cheque reference the office types in, if any.
  reference     text,

  -- The scanned paper receipt, when one is uploaded — the «رفع يدوي مساعد»
  -- half of the owner's dual path. Points at public.attachments.
  attachment_id bigint references public.attachments(id) on delete set null,

  notes         text,

  issued_by     uuid references auth.users(id) on delete set null,
  issued_at     timestamptz not null default now()
);

-- The client's «سنداتي» view and the admin order card both list by order.
create index if not exists receipts_request_id_idx on public.receipts (request_id);
-- Support looks a receipt up by the number the client read out.
create unique index if not exists receipts_serial_idx on public.receipts (serial);

alter table public.receipts enable row level security;

-- ── Policies ────────────────────────────────────────────────────────────────
-- A client may READ the receipts issued against their own orders and nothing
-- else. Nobody may write through RLS at all: issuing a receipt goes through
-- POST /api/v1/admin/receipts behind requireAdmin(), using the service role.
-- Leaving INSERT/UPDATE/DELETE without a policy is what makes that the only
-- door — a permissive insert policy here would let any signed-in user mint a
-- receipt against their own order.
drop policy if exists "receipts_select_own" on public.receipts;
create policy "receipts_select_own" on public.receipts
  for select
  using (
    exists (
      select 1 from public.service_requests sr
      where sr.id = receipts.request_id
        and sr.requester_user_id = auth.uid()
    )
  );

comment on table public.receipts is
  'سندات القبض. Serial is database-generated; issued only through POST /api/v1/admin/receipts.';
