import { Plan } from "./pricing.types";

/**
 * pricing.library.ts
 * ─────────────────────────────────────────────────────────────
 * Stand-alone Library subscription plans.
 * Shown when audience is "lawyers" or "firms" AND libraryMode === true.
 *
 * Pricing (50% launch discount):
 *   lib-q1:     300 SAR / 3 months  (was 600)   → 30-day invite trial
 *   lib-q2:     550 SAR / 6 months  (was 1,050)  → 60-day invite trial
 *   lib-annual: 1,000 SAR / year    (was 2,100)  → 90-day invite trial
 *
 * All plans include:
 *   ✓ Full access to 5,000+ laws, regulations, judicial principles
 *   ✓ AI-powered search
 *   ✓ Daily legislative updates
 *   ✓ 3 colleague invitations for free trial
 * ─────────────────────────────────────────────────────────────
 */

export const plansLibrary: { ar: Plan[]; en: Plan[] } = {
  ar: [
    {
      id: "lib-q1",
      name: "ربع سنوي",
      badge: null,
      priceMonthly: "٣٠٠",
      priceYearly:  "٣٠٠",
      priceOriginal: "٦٠٠",
      periodMonthly: "ر.س / ٣ أشهر",
      periodYearly:  "ر.س / ٣ أشهر",
      desc: "وصول كامل للمكتبة القانونية لمدة ٣ أشهر",
      target: "للتجربة",
      bonusLabel: "خصم ٥٠٪ لفترة الإطلاق",
      pricingFormulaLabel: "حساب لمستخدم واحد (١ مقعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-q1",
      highlighted: false,
      color: "border-blue-200/60",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ١ شهر لكل دعوة)",
        ],
        platform: [
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات",
        ],
        support: ["دعم بريد إلكتروني"],
      },
    },
    {
      id: "lib-q2",
      name: "نصف سنوي",
      badge: "الأكثر اختياراً",
      priceMonthly: "٥٥٠",
      priceYearly:  "٥٥٠",
      priceOriginal: "١٬٠٥٠",
      periodMonthly: "ر.س / ٦ أشهر",
      periodYearly:  "ر.س / ٦ أشهر",
      desc: "وصول كامل للمكتبة القانونية لمدة ٦ أشهر",
      target: "للمحترفين",
      bonusLabel: "خصم ٥٠٪ لفترة الإطلاق",
      pricingFormulaLabel: "حساب لمستخدم واحد (١ مقعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-q2",
      highlighted: true,
      color: "border-royal/20",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ٢ شهر لكل دعوة)",
          "إشعارات تشريعية فورية",
        ],
        platform: [
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات",
          "إضافة للمسودة والحافظة",
        ],
        support: ["دعم واتساب"],
      },
    },
    {
      id: "lib-annual",
      name: "سنوي",
      badge: "الأوفر قيمة",
      priceMonthly: "١٬٠٠٠",
      priceYearly:  "١٬٠٠٠",
      priceOriginal: "٢٬١٠٠",
      periodMonthly: "ر.س / سنة",
      periodYearly:  "ر.س / سنة",
      desc: "وصول كامل للمكتبة القانونية لمدة ١٢ شهراً",
      target: "للمكاتب",
      bonusLabel: "خصم ٥٠٪ لفترة الإطلاق",
      pricingFormulaLabel: "حساب لمستخدم واحد (١ مقعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-annual",
      highlighted: false,
      color: "border-gold/20",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ٣ أشهر لكل دعوة)",
          "إشعارات تشريعية فورية",
          "تصدير نصوص الأنظمة بصيغة PDF",
        ],
        platform: [
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات",
          "إضافة للمسودة والحافظة",
          "مشاركة مقتطفات الأنظمة",
        ],
        support: ["واتساب أولوية", "مدير حساب شخصي"],
      },
    },
  ],
  en: [
    {
      id: "lib-q1",
      name: "Quarterly",
      badge: null,
      priceMonthly: "300",
      priceYearly:  "300",
      priceOriginal: "600",
      periodMonthly: "SAR / 3 months",
      periodYearly:  "SAR / 3 months",
      desc: "Full library access for 3 months",
      target: "Trial",
      bonusLabel: "50% launch discount",
      pricingFormulaLabel: "1 user account (1 seat)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-q1",
      highlighted: false,
      color: "border-blue-200/60",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search",
          "Daily updates as new laws are issued",
          "3 colleague invitations (1-month trial each)",
        ],
        platform: [
          "Focus reading mode",
          "Favorites & notes",
        ],
        support: ["Email support"],
      },
    },
    {
      id: "lib-q2",
      name: "Semi-Annual",
      badge: "Most Popular",
      priceMonthly: "550",
      priceYearly:  "550",
      priceOriginal: "1,050",
      periodMonthly: "SAR / 6 months",
      periodYearly:  "SAR / 6 months",
      desc: "Full library access for 6 months",
      target: "Professionals",
      bonusLabel: "50% launch discount",
      pricingFormulaLabel: "1 user account (1 seat)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-q2",
      highlighted: true,
      color: "border-royal/20",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search",
          "Daily updates as new laws are issued",
          "3 colleague invitations (2-month trial each)",
          "Instant legislative alerts",
        ],
        platform: [
          "Focus reading mode",
          "Favorites & notes",
          "Draft cart & clipboard",
        ],
        support: ["WhatsApp support"],
      },
    },
    {
      id: "lib-annual",
      name: "Annual",
      badge: "Best Value",
      priceMonthly: "1,000",
      priceYearly:  "1,000",
      priceOriginal: "2,100",
      periodMonthly: "SAR / year",
      periodYearly:  "SAR / year",
      desc: "Full library access for 12 months",
      target: "Firms",
      bonusLabel: "50% launch discount",
      pricingFormulaLabel: "1 user account (1 seat)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-annual",
      highlighted: false,
      color: "border-gold/20",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search",
          "Daily updates as new laws are issued",
          "3 colleague invitations (3-month trial each)",
          "Instant legislative alerts",
          "Export law texts as PDF",
        ],
        platform: [
          "Focus reading mode",
          "Favorites & notes",
          "Draft cart & clipboard",
          "Share law excerpts",
        ],
        support: ["Priority WhatsApp", "Dedicated account manager"],
      },
    },
  ],
};

export const plansFirmsLibrary: { ar: Plan[]; en: Plan[] } = {
  ar: [
    {
      id: "lib-firm-small",
      name: "مكتب صغير",
      badge: "١–٥ أعضاء",
      priceMonthly: "٤٬٨٠٠",
      priceYearly:  "٤٬٨٠٠",
      priceOriginal: "٩٬٦٠٠",
      periodMonthly: "ر.س / سنة",
      periodYearly:  "ر.س / سنة",
      desc: "مثالي للمكاتب الصغيرة وفرق العمل المحدودة",
      target: "١–٥ أعضاء",
      bonusLabel: "٣ دعوات للزملاء",
      pricingFormulaLabel: "متاح لـ ١ إلى ٥ مستخدمين (مقاعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-firm-small",
      highlighted: false,
      color: "border-blue-200/60",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية لكل الأعضاء",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ٣ أشهر لكل دعوة)",
        ],
        platform: [
          "١–٥ مقاعد نشطة",
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات المشتركة",
        ],
        support: ["دعم بريد إلكتروني وواتساب"],
      },
    },
    {
      id: "lib-firm-medium",
      name: "شركة متوسطة",
      badge: "٦–٢٠ عضواً",
      priceMonthly: "١٢٬٠٠٠",
      priceYearly:  "١٢٬٠٠٠",
      priceOriginal: "٢٤٬٠٠٠",
      periodMonthly: "ر.س / سنة",
      periodYearly:  "ر.س / سنة",
      desc: "لشركات المحاماة المتوسطة ذات الفرق المتعددة",
      target: "٦–٢٠ عضواً",
      bonusLabel: "٣ دعوات للزملاء",
      pricingFormulaLabel: "متاح لـ ٦ إلى ٢٠ مستخدماً (مقاعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-firm-medium",
      highlighted: true,
      color: "border-royal/20",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية لكل الأعضاء",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ٣ أشهر لكل دعوة)",
        ],
        platform: [
          "٦–٢٠ مقعداً نشطاً",
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات المشتركة",
        ],
        support: ["دعم واتساب أولوية"],
      },
    },
    {
      id: "lib-firm-large",
      name: "شركة كبيرة",
      badge: "٢١–٥٠ عضواً",
      priceMonthly: "٢٤٬٠٠٠",
      priceYearly:  "٢٤٬٠٠٠",
      priceOriginal: "٤٨٬٠٠٠",
      periodMonthly: "ر.س / سنة",
      periodYearly:  "ر.س / سنة",
      desc: "لشركات المحاماة الكبرى والشركاء المتعددين",
      target: "٢١–٥٠ عضواً",
      bonusLabel: "٣ دعوات للزملاء",
      pricingFormulaLabel: "متاح لـ ٢١ إلى ٥٠ مستخدماً (مقاعد)",
      cta: "اشترك الآن",
      ctaHref: "/subscribe?plan=lib-firm-large",
      highlighted: false,
      color: "border-gold/20",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية لكل الأعضاء",
          "تحديثات يومية فور صدور الأنظمة",
          "٣ دعوات لزملائك (تجربة ٣ أشهر لكل دعوة)",
        ],
        platform: [
          "٢١–٥٠ مقعداً نشطاً",
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات المشتركة",
        ],
        support: ["دعم واتساب أولوية", "مدير حساب مخصص"],
      },
    },
    {
      id: "lib-firm-enterprise",
      name: "مؤسسي / Enterprise",
      badge: "٥٠+ عضو",
      priceMonthly: "مخصص",
      priceYearly:  "مخصص",
      periodMonthly: "سنوياً",
      periodYearly:  "سنوياً",
      desc: "للكيانات الكبرى والشبكات القضائية الواسعة",
      target: "٥٠+ عضو",
      bonusLabel: "دعوات مخصصة",
      pricingFormulaLabel: "عدد مقاعد مخصص (٥٠+ مستخدم)",
      cta: "تواصل معنا",
      ctaHref: "/contact",
      highlighted: false,
      color: "border-zinc-200/60 dark:border-white/10",
      features: {
        ai: [
          "وصول كامل لـ +٥٬٠٠٠ نظام ولائحة ومبدأ قضائي",
          "بحث ذكي AI في المكتبة القانونية لكل الأعضاء",
          "تحديثات يومية فور صدور الأنظمة",
          "دعوات للزملاء مخصصة حسب الطلب",
        ],
        platform: [
          "عدد مقاعد غير محدود أو مخصص",
          "قراءة هادئة — وضع التركيز",
          "حفظ المفضلة والملاحظات المشتركة",
        ],
        support: ["دعم على مدار الساعة", "مدير حساب مخصص"],
      },
    },
  ],
  en: [
    {
      id: "lib-firm-small",
      name: "Small Office",
      badge: "1–5 seats",
      priceMonthly: "4,800",
      priceYearly:  "4,800",
      priceOriginal: "9,600",
      periodMonthly: "SAR / year",
      periodYearly:  "SAR / year",
      desc: "Perfect for small offices and limited teams",
      target: "1–5 seats",
      bonusLabel: "3 colleague invites",
      pricingFormulaLabel: "For 1 to 5 users (seats)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-firm-small",
      highlighted: false,
      color: "border-blue-200/60",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search for all team members",
          "Daily updates as new laws are issued",
          "3 colleague invitations (3-month trial each)",
        ],
        platform: [
          "1–5 active seats",
          "Focus reading mode",
          "Shared favorites & notes",
        ],
        support: ["Email & WhatsApp support"],
      },
    },
    {
      id: "lib-firm-medium",
      name: "Medium Firm",
      badge: "6–20 seats",
      priceMonthly: "12,000",
      priceYearly:  "12,000",
      priceOriginal: "24,000",
      periodMonthly: "SAR / year",
      periodYearly:  "SAR / year",
      desc: "For medium law firms with multiple practice groups",
      target: "6–20 seats",
      bonusLabel: "3 colleague invites",
      pricingFormulaLabel: "For 6 to 20 users (seats)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-firm-medium",
      highlighted: true,
      color: "border-royal/20",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search for all team members",
          "Daily updates as new laws are issued",
          "3 colleague invitations (3-month trial each)",
        ],
        platform: [
          "6–20 active seats",
          "Focus reading mode",
          "Shared favorites & notes",
        ],
        support: ["Priority WhatsApp support"],
      },
    },
    {
      id: "lib-firm-large",
      name: "Large Firm",
      badge: "21–50 seats",
      priceMonthly: "24,000",
      priceYearly:  "24,000",
      priceOriginal: "48,000",
      periodMonthly: "SAR / year",
      periodYearly:  "SAR / year",
      desc: "For major law firms and multi-partner networks",
      target: "21–50 seats",
      bonusLabel: "3 colleague invites",
      pricingFormulaLabel: "For 21 to 50 users (seats)",
      cta: "Subscribe Now",
      ctaHref: "/subscribe?plan=lib-firm-large",
      highlighted: false,
      color: "border-gold/20",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search for all team members",
          "Daily updates as new laws are issued",
          "3 colleague invitations (3-month trial each)",
        ],
        platform: [
          "21–50 active seats",
          "Focus reading mode",
          "Shared favorites & notes",
        ],
        support: ["Priority WhatsApp & account manager"],
      },
    },
    {
      id: "lib-firm-enterprise",
      name: "Corporate / Enterprise",
      badge: "50+ seats",
      priceMonthly: "Custom",
      priceYearly:  "Custom",
      periodMonthly: "annually",
      periodYearly:  "annually",
      desc: "For national networks and major judicial entities",
      target: "50+ seats",
      bonusLabel: "Custom invites",
      pricingFormulaLabel: "Custom seat limit (50+ users)",
      cta: "Contact Us",
      ctaHref: "/contact",
      highlighted: false,
      color: "border-zinc-200/60 dark:border-white/10",
      features: {
        ai: [
          "Full access to 5,000+ laws, regulations & principles",
          "AI-powered smart search for all team members",
          "Daily updates as new laws are issued",
          "Custom colleague invites",
        ],
        platform: [
          "Unlimited or custom seats",
          "Focus reading mode",
          "Shared favorites & notes",
        ],
        support: ["24/7 dedicated support & SLA"],
      },
    },
  ],
};
