import { Plan } from "./pricing.types";

// ─── COMPANIES WITH LEGAL DEPT (أرخص — أدوات + نقاط لفريقهم الموجود) ─────────
// الخدمات: نقاط AI (CorpMind/مراجعة عقود/امتثال) + Kanban + مكتبة + سوق مهنيين
// بدون: ترافع أو استشارات محامٍ (لأن عندهم فريق قانوني داخلي أصلاً)
export const plansCompaniesLegalDept: { ar: Plan[]; en: Plan[] } = {
  ar: [
    // ── صغيرة (٦-٤٩) ───────────────────────────────────
    { id: "dept-sm-basic", name: "أساسية", badge: "~٤١٦ ر.س/شهر",
      priceMonthly: "٤,٩٨٨", priceYearly: "٤,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "نقاط AI + مكتبة قانونية + Kanban لفريق صغير", target: "إدارة قانونية صغيرة", cta: "اشترك سنوياً",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-slate-200/50",
      companySize: "small", forLegalDept: true,
      includedSeats: 2, includedAnnualPoints: 5000, extraSeatPrice: "١,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٢ مقعد + ٥,٠٠٠ نقطة", bonusLabel: "٥,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٥,٠٠٠ نقطة سنوية (CorpMind + مراجعة عقود)", "المكتبة القانونية الكاملة ✅", null, null],
        platform: ["٢ مقعد", "Kanban: ١٠ مهام · طلبات: ٥/شهر", "عقود الموظفين (HR) ✅", null],
        support: ["تقارير شهرية", "دعم بريد إلكتروني"],
      },
    },
    { id: "dept-sm-pro", name: "احترافية", badge: "الأكثر اختياراً ⭐",
      priceMonthly: "٩,٩٨٨", priceYearly: "٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "نقاط مكثفة + رادار امتثال + سوق مهنيين", target: "إدارة قانونية صغيرة", cta: "اشترك سنوياً",
      ctaHref: "/register/client?type=company", highlighted: true, color: "border-gold/20",
      companySize: "small", forLegalDept: true,
      includedSeats: 5, includedAnnualPoints: 15000, extraSeatPrice: "١,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٥ مقاعد + ١٥,٠٠٠ نقطة", bonusLabel: "١٥,٠٠٠ نقطة سنوية",
      features: {
        ai: ["١٥,٠٠٠ نقطة سنوية", "رادار امتثال + LegalMail ✅", "حدود صرف بالقسم", null],
        platform: ["٥ مقاعد", "Kanban: ٢٥ مهمة · طلبات: ١٠/شهر", "سوق المهنيين + عقود HR ✅", null],
        support: ["تقارير دورية", "دعم واتساب"],
      },
    },
    { id: "dept-sm-full", name: "متكاملة", badge: "~١,٤٩٩ ر.س/شهر",
      priceMonthly: "١٧,٩٨٨", priceYearly: "١٧,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "محفظة نقاط كبيرة + أدوات AI كاملة + API", target: "إدارة قانونية صغيرة", cta: "اشترك سنوياً",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-royal/20",
      companySize: "small", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "١,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ١٠ مقاعد + ٤٠,٠٠٠ نقطة", bonusLabel: "٤٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٤٠,٠٠٠ نقطة سنوية", "حزمة AI كاملة + تحليل مستندات", "سياسات امتثال مخصصة", null],
        platform: ["١٠ مقاعد", "Kanban: ٥٠ مهمة · ربط API ✅", "سوق + HR + تقارير مالية ✅", null],
        support: ["مدير حساب", "دعم واتساب أولوية"],
      },
    },
    // ── متوسطة (٥٠-٢٤٩) ────────────────────────────────
    { id: "dept-md-basic", name: "أساسية", badge: "~٨٣٣ ر.س/شهر",
      priceMonthly: "٩,٩٨٨", priceYearly: "٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "نقاط + Kanban + مكتبة لفريق قانوني متوسط", target: "إدارة قانونية متوسطة", cta: "اشترك سنوياً",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-slate-200/50",
      companySize: "medium", forLegalDept: true,
      includedSeats: 5, includedAnnualPoints: 15000, extraSeatPrice: "٢,٤٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٥ مقاعد + ١٥,٠٠٠ نقطة", bonusLabel: "١٥,٠٠٠ نقطة سنوية",
      features: {
        ai: ["١٥,٠٠٠ نقطة سنوية", "CorpMind + مراجعة عقود بالنقاط", "المكتبة القانونية الكاملة ✅", null],
        platform: ["٥ مقاعد", "Kanban: ٢٥ مهمة · طلبات: ١٠/شهر", "إدارات + عقود HR ✅", null],
        support: ["تقارير شهرية", "دعم واتساب"],
      },
    },
    { id: "dept-md-pro", name: "احترافية", badge: "الأكثر اختياراً ⭐",
      priceMonthly: "١٩,٩٨٨", priceYearly: "١٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "رادار امتثال + حوكمة + نقاط مكثفة", target: "إدارة قانونية متوسطة", cta: "اشترك سنوياً",
      ctaHref: "/register/client?type=company", highlighted: true, color: "border-gold/20",
      companySize: "medium", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "٢,٤٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ١٠ مقاعد + ٤٠,٠٠٠ نقطة", bonusLabel: "٤٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٤٠,٠٠٠ نقطة سنوية", "رادار امتثال + Deal Intelligence ✅", "حدود صرف بالقسم", null],
        platform: ["١٠ مقاعد", "Kanban: ٥٠ مهمة · حوكمة ✅", "إدارات + تقارير مالية ✅", null],
        support: ["تقارير دورية", "دعم واتساب أولوية"],
      },
    },
    { id: "dept-md-full", name: "متكاملة", badge: "~٢,٩١٦ ر.س/شهر",
      priceMonthly: "٣٤,٩٨٨", priceYearly: "٣٤,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "محفظة ضخمة + AI كامل + حوكمة + API", target: "إدارة قانونية متوسطة", cta: "تواصل معنا",
      ctaHref: "/contact", highlighted: false, color: "border-royal/20",
      companySize: "medium", forLegalDept: true,
      includedSeats: 20, includedAnnualPoints: 80000, extraSeatPrice: "٢,٤٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٢٠ مقعد + ٨٠,٠٠٠ نقطة", bonusLabel: "٨٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٨٠,٠٠٠ نقطة سنوية", "حزمة AI كاملة + فحص صحة ٣٦٠°", "سياسات امتثال مخصصة", null],
        platform: ["٢٠ مقعد", "Kanban: ١٠٠ مهمة · ربط API ✅", "حوكمة + إدارات + تقارير ✅", null],
        support: ["مدير حساب مخصص", "دعم واتساب أولوية"],
      },
    },
    // ── كبيرة (٢٥٠+) ───────────────────────────────────
    { id: "dept-lg-basic", name: "أساسية", badge: "~١,٦٦٦ ر.س/شهر",
      priceMonthly: "١٩,٩٨٨", priceYearly: "١٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "نقاط + حوكمة + أدوات لفريق قانوني مؤسسي", target: "إدارة قانونية كبرى", cta: "تواصل معنا",
      ctaHref: "/contact", highlighted: false, color: "border-slate-200/50",
      companySize: "large", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "٢,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ١٠ مقاعد + ٤٠,٠٠٠ نقطة", bonusLabel: "٤٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٤٠,٠٠٠ نقطة سنوية", "CorpMind + مراجعة عقود بالنقاط", "المكتبة القانونية ✅", null],
        platform: ["١٠ مقاعد", "Kanban: ٤٠ مهمة · حوكمة أساسية", "إدارات + عقود HR ✅", null],
        support: ["تقارير أساسية", "دعم واتساب"],
      },
    },
    { id: "dept-lg-pro", name: "احترافية", badge: "الأكثر اختياراً ⭐",
      priceMonthly: "٣٩,٩٨٨", priceYearly: "٣٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "رادار امتثال كامل + انتداب + نقاط مكثفة", target: "إدارة قانونية كبرى", cta: "تواصل معنا",
      ctaHref: "/contact", highlighted: true, color: "border-gold/20",
      companySize: "large", forLegalDept: true,
      includedSeats: 25, includedAnnualPoints: 100000, extraSeatPrice: "٢,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٢٥ مقعد + ١٠٠,٠٠٠ نقطة", bonusLabel: "١٠٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["١٠٠,٠٠٠ نقطة سنوية", "حزمة AI كاملة + فحص ٣٦٠°", "حدود صرف + امتثال متقدم", null],
        platform: ["٢٥ مقعد", "Kanban: ١٠٠ مهمة · حوكمة كاملة", "انتداب مستشار + تقارير مالية ✅", null],
        support: ["تقارير دورية", "مدير حساب مخصص"],
      },
    },
    { id: "dept-lg-full", name: "متكاملة", badge: "~٦,٦٦٦ ر.س/شهر",
      priceMonthly: "٧٩,٩٨٨", priceYearly: "٧٩,٩٨٨", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "أقصى قوة لإدارة قانونية مؤسسية — API + SSO + إشراف مجتمع", target: "إدارة قانونية كبرى", cta: "تواصل مع المبيعات",
      ctaHref: "/contact", highlighted: false, color: "border-royal/20",
      companySize: "large", forLegalDept: true,
      includedSeats: 50, includedAnnualPoints: 200000, extraSeatPrice: "٢,٩٨٨ ر.س/سنة",
      pricingFormulaLabel: "اشتراك + ٥٠ مقعد + ٢٠٠,٠٠٠ نقطة", bonusLabel: "٢٠٠,٠٠٠ نقطة سنوية",
      features: {
        ai: ["٢٠٠,٠٠٠ نقطة سنوية", "جميع أدوات AI مفتوحة", "سياسات امتثال مخصصة", null],
        platform: ["٥٠ مقعد", "Kanban: ٢٠٠ مهمة · SSO + API ✅", "حوكمة + انتداب + إشراف مجتمع ✅", null],
        support: ["مدير حساب + SLA", "دعم فني ٢٤/٧"],
      },
    },
  ],
  en: [
    // ── Small (6-49) EN ─────────────────────────────────
    { id: "dept-sm-basic", name: "Basic", badge: "~416 SAR/mo",
      priceMonthly: "4,988", priceYearly: "4,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "AI points + legal library + Kanban for small team", target: "Small Legal Dept", cta: "Subscribe Yearly",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-slate-200/50",
      companySize: "small", forLegalDept: true,
      includedSeats: 2, includedAnnualPoints: 5000, extraSeatPrice: "1,988 SAR/yr",
      pricingFormulaLabel: "Annual + 2 seats + 5,000 pts", bonusLabel: "5,000 annual points",
      features: {
        ai: ["5,000 annual points (CorpMind + contract review)", "Full Legal Library ✅", null, null],
        platform: ["2 seats", "Kanban: 10 tasks · Requests: 5/mo", "Employee contracts (HR) ✅", null],
        support: ["Monthly reports", "Email support"],
      },
    },
    { id: "dept-sm-pro", name: "Professional", badge: "Most Popular ⭐",
      priceMonthly: "9,988", priceYearly: "9,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Intensive points + compliance radar + marketplace", target: "Small Legal Dept", cta: "Subscribe Yearly",
      ctaHref: "/register/client?type=company", highlighted: true, color: "border-gold/20",
      companySize: "small", forLegalDept: true,
      includedSeats: 5, includedAnnualPoints: 15000, extraSeatPrice: "1,988 SAR/yr",
      pricingFormulaLabel: "Annual + 5 seats + 15,000 pts", bonusLabel: "15,000 annual points",
      features: {
        ai: ["15,000 annual points", "Compliance radar + LegalMail ✅", "Dept spending limits", null],
        platform: ["5 seats", "Kanban: 25 tasks · Requests: 10/mo", "Marketplace + HR contracts ✅", null],
        support: ["Periodic reports", "WhatsApp support"],
      },
    },
    { id: "dept-sm-full", name: "Full Suite", badge: "~1,499 SAR/mo",
      priceMonthly: "17,988", priceYearly: "17,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Large points wallet + full AI tools + API", target: "Small Legal Dept", cta: "Subscribe Yearly",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-royal/20",
      companySize: "small", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "1,988 SAR/yr",
      pricingFormulaLabel: "Annual + 10 seats + 40,000 pts", bonusLabel: "40,000 annual points",
      features: {
        ai: ["40,000 annual points", "Full AI suite + Doc Analyzer", "Custom compliance policies", null],
        platform: ["10 seats", "Kanban: 50 tasks · API ✅", "Marketplace + HR + Finance reports ✅", null],
        support: ["Account manager", "Priority WhatsApp"],
      },
    },
    // ── Medium (50-249) EN ──────────────────────────────
    { id: "dept-md-basic", name: "Basic", badge: "~833 SAR/mo",
      priceMonthly: "9,988", priceYearly: "9,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Points + Kanban + library for mid-size legal team", target: "Medium Legal Dept", cta: "Subscribe Yearly",
      ctaHref: "/register/client?type=company", highlighted: false, color: "border-slate-200/50",
      companySize: "medium", forLegalDept: true,
      includedSeats: 5, includedAnnualPoints: 15000, extraSeatPrice: "2,488 SAR/yr",
      pricingFormulaLabel: "Annual + 5 seats + 15,000 pts", bonusLabel: "15,000 annual points",
      features: {
        ai: ["15,000 annual points", "CorpMind + contract review by points", "Full Legal Library ✅", null],
        platform: ["5 seats", "Kanban: 25 tasks · Requests: 10/mo", "Departments + HR contracts ✅", null],
        support: ["Monthly reports", "WhatsApp support"],
      },
    },
    { id: "dept-md-pro", name: "Professional", badge: "Most Popular ⭐",
      priceMonthly: "19,988", priceYearly: "19,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Compliance radar + governance + intensive points", target: "Medium Legal Dept", cta: "Subscribe Yearly",
      ctaHref: "/register/client?type=company", highlighted: true, color: "border-gold/20",
      companySize: "medium", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "2,488 SAR/yr",
      pricingFormulaLabel: "Annual + 10 seats + 40,000 pts", bonusLabel: "40,000 annual points",
      features: {
        ai: ["40,000 annual points", "Compliance + Deal Intelligence ✅", "Dept spending limits", null],
        platform: ["10 seats", "Kanban: 50 tasks · Governance ✅", "Departments + Finance reports ✅", null],
        support: ["Periodic reports", "Priority WhatsApp"],
      },
    },
    { id: "dept-md-full", name: "Full Suite", badge: "~2,916 SAR/mo",
      priceMonthly: "34,988", priceYearly: "34,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Massive wallet + full AI + governance + API", target: "Medium Legal Dept", cta: "Contact Us",
      ctaHref: "/contact", highlighted: false, color: "border-royal/20",
      companySize: "medium", forLegalDept: true,
      includedSeats: 20, includedAnnualPoints: 80000, extraSeatPrice: "2,488 SAR/yr",
      pricingFormulaLabel: "Annual + 20 seats + 80,000 pts", bonusLabel: "80,000 annual points",
      features: {
        ai: ["80,000 annual points", "Full AI suite + Health Check 360°", "Custom compliance policies", null],
        platform: ["20 seats", "Kanban: 100 tasks · API ✅", "Governance + Departments + Reports ✅", null],
        support: ["Dedicated account manager", "Priority WhatsApp"],
      },
    },
    // ── Large (250+) EN ─────────────────────────────────
    { id: "dept-lg-basic", name: "Basic", badge: "~1,666 SAR/mo",
      priceMonthly: "19,988", priceYearly: "19,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Points + governance + tools for enterprise legal team", target: "Large Legal Dept", cta: "Contact Us",
      ctaHref: "/contact", highlighted: false, color: "border-slate-200/50",
      companySize: "large", forLegalDept: true,
      includedSeats: 10, includedAnnualPoints: 40000, extraSeatPrice: "2,988 SAR/yr",
      pricingFormulaLabel: "Annual + 10 seats + 40,000 pts", bonusLabel: "40,000 annual points",
      features: {
        ai: ["40,000 annual points", "CorpMind + contract review by points", "Full Legal Library ✅", null],
        platform: ["10 seats", "Kanban: 40 tasks · Basic governance", "Departments + HR contracts ✅", null],
        support: ["Basic reports", "WhatsApp support"],
      },
    },
    { id: "dept-lg-pro", name: "Professional", badge: "Most Popular ⭐",
      priceMonthly: "39,988", priceYearly: "39,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Full compliance + secondment + intensive points", target: "Large Legal Dept", cta: "Contact Us",
      ctaHref: "/contact", highlighted: true, color: "border-gold/20",
      companySize: "large", forLegalDept: true,
      includedSeats: 25, includedAnnualPoints: 100000, extraSeatPrice: "2,988 SAR/yr",
      pricingFormulaLabel: "Annual + 25 seats + 100,000 pts", bonusLabel: "100,000 annual points",
      features: {
        ai: ["100,000 annual points", "Full AI suite + Health Check 360°", "Spending limits + advanced compliance", null],
        platform: ["25 seats", "Kanban: 100 tasks · Full governance", "Secondment + Finance reports ✅", null],
        support: ["Periodic reports", "Dedicated account manager"],
      },
    },
    { id: "dept-lg-full", name: "Full Suite", badge: "~6,666 SAR/mo",
      priceMonthly: "79,988", priceYearly: "79,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Maximum power for enterprise legal — API + SSO + community supervision", target: "Large Legal Dept", cta: "Contact Sales",
      ctaHref: "/contact", highlighted: false, color: "border-royal/20",
      companySize: "large", forLegalDept: true,
      includedSeats: 50, includedAnnualPoints: 200000, extraSeatPrice: "2,988 SAR/yr",
      pricingFormulaLabel: "Annual + 50 seats + 200,000 pts", bonusLabel: "200,000 annual points",
      features: {
        ai: ["200,000 annual points", "All AI tools unlocked", "Custom compliance policies", null],
        platform: ["50 seats", "Kanban: 200 tasks · SSO + API ✅", "Governance + secondment + community ✅", null],
        support: ["Account manager + SLA", "24/7 support"],
      },
    },
  ],
};
