import { Users, Coins, ShieldCheck } from "@phosphor-icons/react";
import { Plan, ComparisonCategory } from "./pricing.types";

export const plansFirms: { ar: Plan[]; en: Plan[] } = {
  ar: [
    {
      id: "firm-basic",
      name: "Firm Basic",
      badge: "~١,٤٩٩ ر.س/شهر",
      priceMonthly: "17,988", priceYearly: "17,988", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "مكتب صغير يحتاج تشغيل قضايا وعملاء وفريق محدود مع نقاط شركة واحدة.",
      target: "مكتب صغير",
      cta: "ابدأ كـمكتب",
      ctaHref: "/register/provider?type=firm",
      highlighted: false,
      color: "border-royal/20",
      includedSeats: 3,
      extraSeatPrice: "2,388 ر.س / سنة",
      minimumSeats: 3,
      maxSeats: 8,
      includedAnnualPoints: 30000,
      pricingFormulaLabel: "اشتراك سنوي + 3 مقاعد + 30,000 نقطة",
      bonusLabel: "30,000 نقطة سنوية للشركة",
      features: {
        ai: ["محفظة نقاط للشركة كلها", "AI قانوني أساسي حسب الرصيد", "نفاد النقاط يوقف الخدمات الاستهلاكية فقط", null],
        platform: ["3 مقاعد مضمّنة", "مقعد إضافي: 2,388 ر.س/سنة", "قضايا وعملاء ومستندات وفريق صغير", "بوابة عميل أساسية"],
        support: ["دعم إعداد أولي", "Beta-ready بدون حفظ خادمي"],
      },
    },
    {
      id: "firm-growth",
      name: "Firm Growth",
      badge: "~٣,٩٩٩ ر.س/شهر ⭐",
      priceMonthly: "47,988", priceYearly: "47,988", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "شركة محاماة نامية تحتاج أقسام وصلاحيات وبوابة عملاء ونقاط قابلة للتوزيع.",
      target: "شركة نامية",
      cta: "اختيار Growth",
      ctaHref: "/register/provider?type=firm",
      highlighted: true,
      color: "border-gold/20",
      includedSeats: 10,
      extraSeatPrice: "2,988 ر.س / سنة",
      minimumSeats: 10,
      maxSeats: 30,
      includedAnnualPoints: 120000,
      pricingFormulaLabel: "اشتراك سنوي + 10 مقاعد + 120,000 نقطة",
      bonusLabel: "120,000 نقطة سنوية قابلة للتوزيع",
      features: {
        ai: ["120,000 نقطة سنوية للشركة", "حدود صرف حسب الدور أو القسم", "AI متقدم عند توفر الرصيد", null],
        platform: ["10 مقاعد مضمّنة", "مقعد إضافي: 2,988 ر.س/سنة", "أقسام ممارسة قانونية", "بوابة عملاء وهوية مكتب"],
        support: ["تقارير تشغيل وفريق", "تجهيز RBAC محلي للربط"],
      },
    },
    {
      id: "firm-scale",
      name: "Firm Scale",
      badge: null,
      priceMonthly: "95,988", priceYearly: "95,988", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "شركة محاماة كبيرة تحتاج حوكمة وفروع وChinese Walls وتحليلات أعمق.",
      target: "شركة كبيرة",
      cta: "اختيار Scale",
      ctaHref: "/register/provider?type=firm",
      highlighted: false,
      color: "border-slate-200/50",
      includedSeats: 25,
      extraSeatPrice: "3,588 ر.س / سنة",
      minimumSeats: 25,
      maxSeats: 75,
      includedAnnualPoints: 360000,
      pricingFormulaLabel: "اشتراك سنوي + 25 مقعد + 360,000 نقطة",
      bonusLabel: "360,000 نقطة سنوية للشركة",
      features: {
        ai: ["360,000 نقطة سنوية", "ميزانيات نقاط للإدارات", "OCR وترجمة وتحليل مستندات حسب الرصيد", null],
        platform: ["25 مقعد مضمّن", "مقعد إضافي: 3,588 ر.س/سنة", "حوكمة وChinese Walls", "فروع وغرف مشتركة وتحليلات"],
        support: ["إعداد حوكمة", "سجل تدقيق Backend-ready"],
      },
    },
    {
      id: "firm-enterprise",
      name: "Firm Enterprise",
      badge: "مخصص",
      priceMonthly: "179,988+", priceYearly: "179,988+", periodMonthly: "ر.س / سنة", periodYearly: "ر.س / سنة",
      desc: "شبكة فروع أو شركة محاماة كبرى تحتاج عقدا مخصصا ونقاطا وسعة حسب الاتفاق.",
      target: "Enterprise",
      cta: "تواصل مع المبيعات",
      ctaHref: "/contact",
      highlighted: false,
      color: "border-[#C8A762]/25",
      includedSeats: 50,
      extraSeatPrice: "مخصص",
      minimumSeats: 50,
      maxSeats: null,
      includedAnnualPoints: 900000,
      pricingFormulaLabel: "عقد سنوي + 50 مقعد + نقاط مخصصة",
      bonusLabel: "900,000+ نقطة أو حسب العقد",
      features: {
        ai: ["900,000+ نقطة سنوية أو مخصصة", "سياسات صرف متقدمة", "جاهزية SSO/API لاحقا", null],
        platform: ["50 مقعد مضمّن", "مقاعد إضافية حسب العقد", "فروع وشركاء وOf Counsel", "SLA وإعدادات خاصة لاحقا"],
        support: ["مدير نجاح مخصص", "مراجعة أمنية وتشغيلية قبل الإنتاج"],
      },
    },
  ],
  en: [
    {
      id: "firm-basic",
      name: "Firm Basic",
      badge: "~1,499 SAR/mo",
      priceMonthly: "17,988", priceYearly: "17,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Small office operations with seats and one shared firm points wallet.",
      target: "Small Firm",
      cta: "Start as Firm",
      ctaHref: "/register/provider?type=firm",
      highlighted: false,
      color: "border-royal/20",
      includedSeats: 3,
      extraSeatPrice: "2,388 SAR / year",
      minimumSeats: 3,
      maxSeats: 8,
      includedAnnualPoints: 30000,
      pricingFormulaLabel: "Annual subscription + 3 seats + 30,000 points",
      bonusLabel: "30,000 annual firm points",
      features: {
        ai: ["Shared firm points wallet", "Core legal AI by balance", "Exhaustion blocks consumption only", null],
        platform: ["3 included seats", "Extra seat: 2,388 SAR/year", "Cases, clients, documents, small team", "Basic client portal"],
        support: ["Initial setup", "Beta-ready without production save"],
      },
    },
    {
      id: "firm-growth",
      name: "Firm Growth",
      badge: "~3,999 SAR/mo ⭐",
      priceMonthly: "47,988", priceYearly: "47,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Growing law firms with departments, permissions, client portal, and shared points.",
      target: "Growing Firm",
      cta: "Choose Growth",
      ctaHref: "/register/provider?type=firm",
      highlighted: true,
      color: "border-gold/20",
      includedSeats: 10,
      extraSeatPrice: "2,988 SAR / year",
      minimumSeats: 10,
      maxSeats: 30,
      includedAnnualPoints: 120000,
      pricingFormulaLabel: "Annual subscription + 10 seats + 120,000 points",
      bonusLabel: "120,000 annual allocatable points",
      features: {
        ai: ["120,000 annual firm points", "Role or department usage limits", "Advanced AI when balance is available", null],
        platform: ["10 included seats", "Extra seat: 2,988 SAR/year", "Practice departments", "Client portal and firm branding"],
        support: ["Team reports", "Local RBAC ready for backend"],
      },
    },
    {
      id: "firm-scale",
      name: "Firm Scale",
      badge: null,
      priceMonthly: "95,988", priceYearly: "95,988", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Large firms needing governance, branches, Chinese Walls, and deeper analytics.",
      target: "Large Firm",
      cta: "Choose Scale",
      ctaHref: "/register/provider?type=firm",
      highlighted: false,
      color: "border-slate-200/50",
      includedSeats: 25,
      extraSeatPrice: "3,588 SAR / year",
      minimumSeats: 25,
      maxSeats: 75,
      includedAnnualPoints: 360000,
      pricingFormulaLabel: "Annual subscription + 25 seats + 360,000 points",
      bonusLabel: "360,000 annual firm points",
      features: {
        ai: ["360,000 annual points", "Department point budgets", "OCR, translation, and bulk analysis by balance", null],
        platform: ["25 included seats", "Extra seat: 3,588 SAR/year", "Governance and Chinese Walls", "Branches, shared rooms, analytics"],
        support: ["Governance setup", "Backend-ready audit trail"],
      },
    },
    {
      id: "firm-enterprise",
      name: "Firm Enterprise",
      badge: "Custom",
      priceMonthly: "179,988+", priceYearly: "179,988+", periodMonthly: "SAR / year", periodYearly: "SAR / year",
      desc: "Large networks and enterprise firms with custom capacity, points, and support.",
      target: "Enterprise",
      cta: "Contact Sales",
      ctaHref: "/contact",
      highlighted: false,
      color: "border-[#C8A762]/25",
      includedSeats: 50,
      extraSeatPrice: "Custom",
      minimumSeats: 50,
      maxSeats: null,
      includedAnnualPoints: 900000,
      pricingFormulaLabel: "Annual contract + 50 seats + custom points",
      bonusLabel: "900,000+ points or custom",
      features: {
        ai: ["900,000+ annual points or custom", "Advanced consumption policies", "Future SSO/API readiness", null],
        platform: ["50 included seats", "Additional seats by contract", "Branches, partners, Of Counsel", "Future SLA and custom settings"],
        support: ["Dedicated success manager", "Security and rollout review before production"],
      },
    },
  ],
};

export const comparisonFirms: { ar: ComparisonCategory[]; en: ComparisonCategory[] } = {
  ar: [
    {
      category: "الاشتراك والمقاعد",
      icon: Users,
      rows: [
        { feature: "طريقة الدفع", "firm-basic": "سنوي", "firm-growth": "سنوي", "firm-scale": "سنوي", "firm-enterprise": "عقد سنوي" },
        { feature: "المقاعد المضمّنة", "firm-basic": "3", "firm-growth": "10", "firm-scale": "25", "firm-enterprise": "50+" },
        { feature: "سعر المقعد الإضافي", "firm-basic": "2,388/سنة", "firm-growth": "2,988/سنة", "firm-scale": "3,588/سنة", "firm-enterprise": "مخصص" },
      ],
    },
    {
      category: "النقاط والاستهلاك",
      icon: Coins,
      rows: [
        { feature: "نقاط سنوية للشركة", "firm-basic": "30,000", "firm-growth": "120,000", "firm-scale": "360,000", "firm-enterprise": "900,000+" },
        { feature: "ميزانيات أقسام", "firm-basic": "لا", "firm-growth": "أساسي", "firm-scale": "متقدم", "firm-enterprise": "مخصص" },
        { feature: "عند نفاد النقاط", "firm-basic": "تتوقف خدمات الاستهلاك فقط", "firm-growth": "تتوقف خدمات الاستهلاك فقط", "firm-scale": "تتوقف خدمات الاستهلاك فقط", "firm-enterprise": "حسب العقد" },
      ],
    },
    {
      category: "التشغيل والحوكمة",
      icon: ShieldCheck,
      rows: [
        { feature: "أقسام ممارسة قانونية", "firm-basic": "لا", "firm-growth": "نعم", "firm-scale": "نعم", "firm-enterprise": "مخصص" },
        { feature: "Chinese Walls", "firm-basic": "لا", "firm-growth": "لا", "firm-scale": "نعم", "firm-enterprise": "نعم" },
        { feature: "بوابة العملاء", "firm-basic": "أساسية", "firm-growth": "كاملة", "firm-scale": "كاملة", "firm-enterprise": "مخصصة" },
      ],
    },
  ],
  en: [
    {
      category: "Subscription & Seats",
      icon: Users,
      rows: [
        { feature: "Billing", "firm-basic": "Annual", "firm-growth": "Annual", "firm-scale": "Annual", "firm-enterprise": "Annual contract" },
        { feature: "Included seats", "firm-basic": "3", "firm-growth": "10", "firm-scale": "25", "firm-enterprise": "50+" },
        { feature: "Extra seat", "firm-basic": "2,388/year", "firm-growth": "2,988/year", "firm-scale": "3,588/year", "firm-enterprise": "Custom" },
      ],
    },
    {
      category: "Points & Usage",
      icon: Coins,
      rows: [
        { feature: "Annual firm points", "firm-basic": "30,000", "firm-growth": "120,000", "firm-scale": "360,000", "firm-enterprise": "900,000+" },
        { feature: "Department budgets", "firm-basic": "No", "firm-growth": "Basic", "firm-scale": "Advanced", "firm-enterprise": "Custom" },
        { feature: "If points run out", "firm-basic": "Consumption services pause only", "firm-growth": "Consumption services pause only", "firm-scale": "Consumption services pause only", "firm-enterprise": "By contract" },
      ],
    },
    {
      category: "Operations & Governance",
      icon: ShieldCheck,
      rows: [
        { feature: "Practice departments", "firm-basic": "No", "firm-growth": "Yes", "firm-scale": "Yes", "firm-enterprise": "Custom" },
        { feature: "Chinese Walls", "firm-basic": "No", "firm-growth": "No", "firm-scale": "Yes", "firm-enterprise": "Yes" },
        { feature: "Client portal", "firm-basic": "Basic", "firm-growth": "Full", "firm-scale": "Full", "firm-enterprise": "Custom" },
      ],
    },
  ],
};
