import { Brain, Gavel, Users, UsersThree, ShieldCheck, Scales, Sparkle } from "@phosphor-icons/react";
import { Plan, ComparisonCategory } from "./pricing.types";

// ─── Plans: Individuals Pricing Pyramid (Owner & Council Decisions 165/168) ──
// 1. pay-per-piece: الدفع بالعمل القانوني المقطوع (بدون اشتراك)
// 2. ind-ai: الباقة الذكية (٣٩ ر.س / شهر أو ٣٩٠ ر.س / سنة) — ذكاء اصطناعي ذاتي
// 3. ind-preventive: الباقة الوقائية (١٤٩ ر.س / شهر أو ١٬٤٩٠ ر.س / سنة) — استشارات وعقود
// 4. ind-litigation: باقة الخصومة والتقاضي (٣٩٩ ر.س / شهر أو ٣٬٩٩٠ ر.س / سنة) [تخضع لضوابط الاكتتاب]
// 5. ind-family: الباقة العائلية الشاملة (٦٩٩ ر.س / شهر أو ٦٬٩٩٠ ر.س / سنة) — حتى ٥ أفراد

export const plansIndividuals: { ar: Plan[]; en: Plan[] } = {
  ar: [
    {
      id: "pay-per-piece",
      name: "الدفع بالعمل القانوني",
      badge: "بدون اشتراك",
      priceMonthly: "حسب الخدمة",
      priceYearly: "بدون اشتراك",
      periodMonthly: "تسعير مقطوع لكل عمل",
      periodYearly: "ادفع فقط مقابل ما تطلبه",
      desc: "صياغة مذكرات، عقود، وترافع قضائي متخصص — ادفع فقط عند الحاجة دون أي التزام سنوي",
      target: "أفراد",
      cta: "اطلب خدمة الآن",
      ctaHref: "/dashboard/client/draft",
      highlighted: false,
      color: "border-slate-300",
      isBetaHidden: false,
      features: {
        ai: [
          "استشارة مرئية مع محامٍ مرخّص (٣٠ دقيقة) = ٢٥٠ ر.س",
          "صياغة مذكرة رد / جوابية = ١,٥٠٠ ر.س",
          "مراجعة وتدقيق عقد = ٨٠٠ ر.س",
          "لائحة استئناف / نقض = تبدأ من ٣,٠٠٠ ر.س",
        ],
        platform: [
          "تمثيل قضائي وترافع مخصص من محامٍ مرخّص",
          "حجز الرسوم في محفظة الضمان المالي (Escrow)",
          "فحص تعارض المصالح والتدقيق المكتبي قبل التسليم",
          "لا يوجد أي اشتراك دوري أو رسوم خفية",
        ],
        support: ["متابعة مسار الطلب عبر المنصة", "تحديثات دورية حتى اكتمال الخدمة"],
      },
    },
    {
      id: "ind-ai",
      isBetaHidden: false,
      name: "الباقة الذكية (AI الذاتي)",
      badge: "ريال وربع يومياً",
      bonusLabel: "وفر شهرين عند الدفع السنوي",
      priceMonthly: "٣٩",
      priceYearly: "٣٩٠",
      priceOriginal: "٤٦٨",
      periodMonthly: "ر.س / شهر",
      periodYearly: "ر.س / سنة",
      desc: "مستشارك القانوني الذكي على مدار الساعة — إجابات نظامية فورية وصياغة خطابات وإنذارات",
      target: "الأفراد والمستقلون والموظفون",
      cta: "اشترك في الباقة الذكية",
      ctaHref: "/register/client?type=individual&plan=ind-ai",
      highlighted: false,
      color: "border-emerald-300",
      features: {
        ai: [
          "ذكاء اصطناعي قانوني غير محدود طوال الاشتراك",
          "استشهاد مباشر وفوري بمواد الأنظمة واللوائح السعودية",
          "توليد ومراجعة مسودات الخطابات والإنذارات الرسمية",
          "حاسبة الرسوم القضائية ومحدد مدد التقادم النظامية",
        ],
        platform: [
          "حساب رقمي متكامل لحفظ استفساراتك واستشاراتك",
          "إمكانية شراء استشارات محامين مرخصين بأسعار تفضيلية",
          "تحديثات يومية بالتغييرات التشريعية التي تهم الأفراد",
          "لا تتطلب أي فحص طبي أو موافقة مسبقة",
        ],
        support: ["دعم فني عبر المنصة والبريد"],
      },
    },
    {
      id: "ind-preventive",
      isBetaHidden: false,
      name: "الباقة الوقائية (استشارات وعقود)",
      badge: "الأكثر طلباً للأفراد",
      bonusLabel: "وفر شهرين عند الدفع السنوي",
      priceMonthly: "١٤٩",
      priceYearly: "١٬٤٩٠",
      priceOriginal: "١٬٧٨٨",
      periodMonthly: "ر.س / شهر",
      periodYearly: "ر.س / سنة",
      desc: "درعك الوقائي لحماية حقوقك وتعاملاتك اليومية — استشارات مع محامين مرخصين ومراجعة عقود",
      target: "الموظفون ورجال الأعمال المستقلون",
      cta: "اشترك في الباقة الوقائية",
      ctaHref: "/register/client?type=individual&plan=ind-preventive",
      highlighted: true,
      color: "border-royal/30 shadow-md",
      features: {
        ai: [
          "كل مزايا الباقة الذكية (ذكاء اصطناعي مفتوح)",
          "فحص وقائي تعاقدي وتنبيهات بالمخاطر القانونية",
          "مسودات عقود جاهزة ومعتمدة حسب الأنظمة",
          "تدقيق ومقارنة بنود العقود",
        ],
        platform: [
          "٤ استشارات قانونية سنوية (مرئية/هاتفية) مع محامٍ مرخّص",
          "مراجعة وتدقيق عقدين (٢) سنوياً لضمان خلوها من الثغرات",
          "خصم مستمر ١٥٪ على أتعاب الترافع وكافة القضايا",
          "مراجعة دورية لملفك العقدي والقانوني",
        ],
        support: ["دعم مباشر ومسار سريع عبر واتساب"],
      },
    },
    {
      id: "ind-litigation",
      isBetaHidden: false,
      name: "باقة الخصومة والتقاضي",
      badge: "تخضع لقواعد الاكتتاب والقبول",
      bonusLabel: "تمثيل وترافع أمام المحاكم",
      priceMonthly: "٣٩٩",
      priceYearly: "٣٬٩٩٠",
      priceOriginal: "٤٬٧٨٨",
      periodMonthly: "ر.س / شهر",
      periodYearly: "ر.س / سنة",
      desc: "تمثيل قضائي وترافع معتمد أمام المحاكم — تخضع للتدقيق المهني المسبق وخلو النزاع من التعارض",
      target: "أصحاب النزاعات والقضايا المتداولة",
      cta: "طلب الانضمام للباقة",
      ctaHref: "/register/client?type=individual&plan=ind-litigation",
      highlighted: false,
      color: "border-amber-400",
      features: {
        ai: [
          "كل مزايا الباقتين الذكية والوقائية",
          "صياغة لوائح الدعوى والمذكرات الجوابية والاعتراضية",
          "محاكاة الجلسات وتوقع دفوع الخصم (Wargaming)",
          "تحليل السوابق القضائية المماثلة للنزاع",
        ],
        platform: [
          "تمثيل قضائي وترافع أمام المحاكم لقضية مؤهلة سنوياً",
          "استشارات غير محدودة طوال فترة التقاضي في القضية المقبولة",
          "حجز الأتعاب في محفظة الضمان المالي المعتمدة",
          "⚠️ تخضع القضية للفحص المهني وضوابط الاكتتاب قبل التفعيل",
        ],
        support: ["خط ساخن ومتابعة مخصصة مع المحامي المسؤول"],
      },
    },
    {
      id: "ind-family",
      isBetaHidden: false,
      name: "الباقة العائلية الشاملة",
      badge: "تغطي حتى ٥ أفراد",
      bonusLabel: "وفر ٥٥٪ مقارنة بالاشتراكات الفردية",
      priceMonthly: "٦٩٩",
      priceYearly: "٦٬٩٩٠",
      priceOriginal: "٨٬٣٨٨",
      periodMonthly: "ر.س / شهر",
      periodYearly: "ر.س / سنة",
      desc: "مظلة حماية قانونية متكاملة لجميع أفراد الأسرة مع استقلالية تامة للخصوصية وضامن موحد",
      target: "العائلات حتى ٥ أفراد",
      cta: "ابدأ الباقة العائلية",
      ctaHref: "/register/client?type=individual&plan=ind-family",
      highlighted: false,
      color: "border-[#C8A762]",
      features: {
        ai: [
          "ذكاء اصطناعي قانوني مفتوح ومستقل لكل فرد في حسابه الخاص",
          "استشهادات نظامية وفحص عقود الإيجار والعمل للأسرة",
          "توليد الخطابات ومسودات الاتفاقات العائلية",
          "حسابات مستقلة لكل فرد تحترم خصوصيته الكاملة",
        ],
        platform: [
          "١٠ استشارات قانونية سنوية موزعة على أفراد العائلة مع محامين مرخصين",
          "صياغة وتدقيق ٤ عقود سنوية (إيجار، عمل، بيع، تركات)",
          "خصم ٢٥٪ على أتعاب الترافع وكافة القضايا لجميع أفراد العائلة",
          "ضامن مالي موحد (Master Payer) مع عزل تام للبيانات (RLS)",
        ],
        support: ["أولوية قصوى على خط الدعم العائلي المخصص"],
      },
    },
  ],
  en: [
    {
      id: "pay-per-piece",
      name: "Pay Per Legal Work",
      badge: "No Subscription",
      priceMonthly: "Per Service",
      priceYearly: "0 SAR",
      periodMonthly: "Fixed fee per deliverable",
      periodYearly: "Pay only for what you need",
      desc: "Drafting briefs, contracts, and court representation — on-demand legal services without subscription commitments",
      target: "Individuals",
      cta: "Request Service",
      ctaHref: "/dashboard/client/draft",
      highlighted: false,
      color: "border-slate-300",
      isBetaHidden: false,
      features: {
        ai: [
          "Video consultation with a licensed lawyer (30 min) = SAR 250",
          "Statement of defense / reply brief drafting = SAR 1,500",
          "Contract review & legal audit = SAR 800",
          "Appeals & cassation briefs = Starts at SAR 3,000",
        ],
        platform: [
          "Full court representation by licensed Saudi attorneys",
          "Funds held safely in escrow until client approval",
          "Conflict-of-interest checks & internal quality gates",
          "Zero recurring fees or hidden charges",
        ],
        support: ["Real-time case tracking on platform", "Direct administrative updates"],
      },
    },
    {
      id: "ind-ai",
      isBetaHidden: false,
      name: "Smart AI Self-Service",
      badge: "Daily Peace of Mind",
      bonusLabel: "Save 2 months on annual billing",
      priceMonthly: "39",
      priceYearly: "390",
      priceOriginal: "468",
      periodMonthly: "SAR / month",
      periodYearly: "SAR / year",
      desc: "Your 24/7 AI legal assistant — instant statutory answers and draft notices",
      target: "Individuals, Employees & Freelancers",
      cta: "Subscribe to Smart AI",
      ctaHref: "/register/client?type=individual&plan=ind-ai",
      highlighted: false,
      color: "border-emerald-300",
      features: {
        ai: [
          "Unlimited 24/7 AI legal assistant",
          "Direct citations from Saudi statutory laws",
          "Draft generation for notices and official correspondence",
          "Court fees & limitation period calculators",
        ],
        platform: [
          "Full digital profile to archive your questions and drafts",
          "Access to licensed lawyer consultations at discounted rates",
          "Daily updates on statutory changes relevant to individuals",
          "Zero underwriting or medical qualification required",
        ],
        support: ["Platform & email technical support"],
      },
    },
    {
      id: "ind-preventive",
      isBetaHidden: false,
      name: "Preventive Legal Shield",
      badge: "Most Popular",
      bonusLabel: "Save 2 months on annual billing",
      priceMonthly: "149",
      priceYearly: "1,490",
      priceOriginal: "1,788",
      periodMonthly: "SAR / month",
      periodYearly: "SAR / year",
      desc: "Your preventive legal shield — licensed lawyer consultations and contract reviews",
      target: "Professionals & Working Individuals",
      cta: "Subscribe to Preventive",
      ctaHref: "/register/client?type=individual&plan=ind-preventive",
      highlighted: true,
      color: "border-royal/30 shadow-md",
      features: {
        ai: [
          "All Smart AI features included",
          "Contract health check & risk warnings",
          "Verified statutory agreement templates",
          "Clause-by-clause comparison and audit",
        ],
        platform: [
          "4 annual consultations (video/phone) with licensed lawyers",
          "2 contract reviews per year for clause risk protection",
          "Permanent 15% discount on additional litigation services",
          "Periodic contractual portfolio review",
        ],
        support: ["Priority WhatsApp technical & procedural support"],
      },
    },
    {
      id: "ind-litigation",
      isBetaHidden: false,
      name: "Litigation & Representation",
      badge: "Subject to Underwriting",
      bonusLabel: "Full Court Representation",
      priceMonthly: "399",
      priceYearly: "3,990",
      priceOriginal: "4,788",
      periodMonthly: "SAR / month",
      periodYearly: "SAR / year",
      desc: "Court representation & litigation defense — subject to underwriting review and conflict checks",
      target: "Litigants & Dispute Parties",
      cta: "Apply for Litigation Plan",
      ctaHref: "/register/client?type=individual&plan=ind-litigation",
      highlighted: false,
      color: "border-amber-400",
      features: {
        ai: [
          "All Smart AI & Preventive features included",
          "Drafting claims, responses, and appeals",
          "Trial simulation and rebuttal wargaming",
          "Precedent matching and court case analysis",
        ],
        platform: [
          "Court representation for 1 qualified eligible case per year",
          "Unlimited consultations throughout active case duration",
          "Escrow protection for legal dispute fees",
          "⚠️ Subject to legal underwriting review and intake qualification",
        ],
        support: ["Direct case manager & attorney hotline"],
      },
    },
    {
      id: "ind-family",
      isBetaHidden: false,
      name: "Family Legal Umbrella",
      badge: "Up to 5 Family Members",
      bonusLabel: "Save up to 55% vs individual plans",
      priceMonthly: "699",
      priceYearly: "6,990",
      priceOriginal: "8,388",
      periodMonthly: "SAR / month",
      periodYearly: "SAR / year",
      desc: "Comprehensive family legal protection with full member privacy and a unified master payer",
      target: "Families up to 5 members",
      cta: "Start Family Umbrella",
      ctaHref: "/register/client?type=individual&plan=ind-family",
      highlighted: false,
      color: "border-[#C8A762]",
      features: {
        ai: [
          "Independent unlimited AI accounts for each family member",
          "Statutory citations, lease checks, and employment advice",
          "Drafting notices and family settlement agreements",
          "Private member profiles ensuring individual confidentiality",
        ],
        platform: [
          "10 annual licensed lawyer consultations across members",
          "Drafting & review of 4 annual family contracts",
          "25% discount on litigation fees for all family members",
          "Single Master Payer guarantor with full RLS data separation",
        ],
        support: ["VIP family dedicated concierge support line"],
      },
    },
  ],
};

// ─── Comparison Tables: Individuals ──────────────────────────────────────────
export const comparisonIndividuals: { ar: ComparisonCategory[]; en: ComparisonCategory[] } = {
  ar: [
    {
      category: "الذكاء الاصطناعي والوقاية",
      icon: Brain,
      rows: [
        { feature: "الذكاء الاصطناعي القانوني",   "pay-per-piece": "محدود",          "ind-ai": "غير محدود",            "ind-preventive": "غير محدود",            "ind-litigation": "غير محدود",            "ind-family": "مستقل لكل فرد" },
        { feature: "الاستشهاد بالمواد النظامية",  "pay-per-piece": true,            "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": true },
        { feature: "فحص وتدقيق العقود",          "pay-per-piece": "٨٠٠ ر.س/عقد",    "ind-ai": "خصم ١٠٪",              "ind-preventive": "عقدان مجاناً/سنة",     "ind-litigation": "شامل عقود النزاع",     "ind-family": "٤ عقود مجاناً/سنة" },
        { feature: "صياغة الخطابات والإنذارات",   "pay-per-piece": "حسب الخدمة",     "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": true },
      ],
    },
    {
      category: "المحامي المرخّص والتمثيل القضائي",
      icon: Gavel,
      rows: [
        { feature: "استشارات مع محامٍ مرخّص",    "pay-per-piece": "٢٥٠ ر.س/جلسة",   "ind-ai": "سعر تفضيلي",           "ind-preventive": "٤ استشارات/سنة",       "ind-litigation": "غير محدودة للقضية",    "ind-family": "١٠ استشارات/سنة" },
        { feature: "خصم أتعاب الترافع والقضايا", "pay-per-piece": "-",              "ind-ai": "٥٪",                   "ind-preventive": "١٥٪",                  "ind-litigation": "قضية مشمولة بالكامل",  "ind-family": "٢٥٪ لكل العائلة" },
        { feature: "تمثيل قضائي وترافع بالمحاكم", "pay-per-piece": "أتعاب متفق عليها","ind-ai": "-",                   "ind-preventive": "بخصم ١٥٪",             "ind-litigation": "قضية مؤهلة سنوياً",    "ind-family": "بخصم ٢٥٪" },
        { feature: "ضوابط القبول والاكتتاب",      "pay-per-piece": "فحص تعارض",     "ind-ai": "قبول فوري",            "ind-preventive": "قبول فوري",            "ind-litigation": "تخضع للفحص المهني",    "ind-family": "قبول فوري" },
      ],
    },
    {
      category: "هيكل الاشتراك والمجموعة",
      icon: UsersThree,
      rows: [
        { feature: "عدد المستفيدين",             "pay-per-piece": "فرد",           "ind-ai": "فرد واحد",             "ind-preventive": "فرد واحد",             "ind-litigation": "صاحب القضية",          "ind-family": "حتى ٥ أفراد" },
        { feature: "طريقة السداد",                "pay-per-piece": "عند الطلب",     "ind-ai": "شهري / سنوي",          "ind-preventive": "شهري / سنوي",          "ind-litigation": "شهري / سنوي",          "ind-family": "ضامن مالي موحد" },
        { feature: "عزل الخصوصية (RLS)",         "pay-per-piece": true,            "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": "١٠٠٪ معزول لكل عضو" },
      ],
    },
    {
      category: "التكلفة والدعم",
      icon: ShieldCheck,
      rows: [
        { feature: "سعر الاشتراك الشهري",         "pay-per-piece": "صفر ر.س",       "ind-ai": "٣٩ ر.س",               "ind-preventive": "١٤٩ ر.س",              "ind-litigation": "٣٩٩ ر.س",              "ind-family": "٦٩٩ ر.س" },
        { feature: "سعر الاشتراك السنوي",         "pay-per-piece": "صفر ر.س",       "ind-ai": "٣٩٠ ر.س",              "ind-preventive": "١٬٤٩٠ ر.س",            "ind-litigation": "٣٬٩٩٠ ر.س",            "ind-family": "٦٬٩٩٠ ر.س" },
        { feature: "مستوى الدعم الفني",           "pay-per-piece": "دعم للطلب",     "ind-ai": "دعم عبر المنصة",       "ind-preventive": "واتساب أولوية",        "ind-litigation": "مدير قضية مخصص",       "ind-family": "خط عائلي مباشر VIP" },
      ],
    },
  ],
  en: [
    {
      category: "AI & Preventive Law",
      icon: Brain,
      rows: [
        { feature: "Legal AI Queries",            "pay-per-piece": "Limited",       "ind-ai": "Unlimited",            "ind-preventive": "Unlimited",            "ind-litigation": "Unlimited",            "ind-family": "Private per member" },
        { feature: "Statutory Article Citations", "pay-per-piece": true,            "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": true },
        { feature: "Contract Audit & Review",     "pay-per-piece": "SAR 800/contract","ind-ai": "10% off",            "ind-preventive": "2 free/year",          "ind-litigation": "Case contracts included","ind-family": "4 free/year" },
        { feature: "Notice & Letter Drafting",    "pay-per-piece": "Per service",   "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": true },
      ],
    },
    {
      category: "Licensed Lawyers & Court Cases",
      icon: Gavel,
      rows: [
        { feature: "Lawyer Consultations",        "pay-per-piece": "SAR 250/session","ind-ai": "Discounted rate",      "ind-preventive": "4 sessions/year",      "ind-litigation": "Unlimited for case",   "ind-family": "10 sessions/year" },
        { feature: "Litigation Fees Discount",    "pay-per-piece": "-",             "ind-ai": "5%",                   "ind-preventive": "15%",                  "ind-litigation": "Fully covered case",   "ind-family": "25% for family" },
        { feature: "Court Representation",        "pay-per-piece": "Agreed fee",    "ind-ai": "-",                    "ind-preventive": "15% off fee",          "ind-litigation": "1 eligible case/year", "ind-family": "25% off fee" },
        { feature: "Underwriting & Intake Check", "pay-per-piece": "Conflict check","ind-ai": "Instant activation",   "ind-preventive": "Instant activation",   "ind-litigation": "Requires review gate", "ind-family": "Instant activation" },
      ],
    },
    {
      category: "Subscription & Group Architecture",
      icon: UsersThree,
      rows: [
        { feature: "Number of Members",           "pay-per-piece": "Solo",          "ind-ai": "Solo",                 "ind-preventive": "Solo",                 "ind-litigation": "Litigant",             "ind-family": "Up to 5 members" },
        { feature: "Billing Mechanism",           "pay-per-piece": "On demand",     "ind-ai": "Monthly / Yearly",     "ind-preventive": "Monthly / Yearly",     "ind-litigation": "Monthly / Yearly",     "ind-family": "Single Master Payer" },
        { feature: "Data Privacy Isolation (RLS)","pay-per-piece": true,            "ind-ai": true,                   "ind-preventive": true,                   "ind-litigation": true,                   "ind-family": "100% private per member" },
      ],
    },
    {
      category: "Pricing & Support",
      icon: ShieldCheck,
      rows: [
        { feature: "Monthly Subscription Price",  "pay-per-piece": "0 SAR",         "ind-ai": "39 SAR",               "ind-preventive": "149 SAR",              "ind-litigation": "399 SAR",              "ind-family": "699 SAR" },
        { feature: "Annual Subscription Price",   "pay-per-piece": "0 SAR",         "ind-ai": "390 SAR",              "ind-preventive": "1,490 SAR",            "ind-litigation": "3,990 SAR",            "ind-family": "6,990 SAR" },
        { feature: "Support Level",               "pay-per-piece": "Order support", "ind-ai": "Platform support",      "ind-preventive": "Priority WhatsApp",    "ind-litigation": "Dedicated case manager","ind-family": "VIP family hotline" },
      ],
    },
  ],
};
