import { Brain, Gavel, Users, UsersThree, ShieldCheck } from "@phosphor-icons/react";
import { Plan, ComparisonCategory } from "./pricing.types";

// ─── Plans: Individuals (3 plans max — Council Refactored) ───────────────────
// 1. pay-per-piece: الدفع بالعمل القانوني المقطوع (بدون اشتراك)
// 2. shield: التأمين القانوني الفردي (٣٦٥ ر.س/سنة أو عرض التأسيس ٢٩٦ ر.س لأول ٣٩٦ عميلاً مؤسساً)
// 3. group: التأمين القانوني الجماعي - الرَّبع (تسعير مدرج يبدأ من ٧٥٠ ر.س لـ ٣ أفراد وضامن مالي موحد)
export const plansIndividuals: { ar: Plan[]; en: Plan[] } = {
  ar: [
    {
      id: "pay-per-piece",
      name: "الدفع بالعمل القانوني",
      badge: "بدون اشتراك",
      priceMonthly: "حسب الخدمة",
      priceYearly: "بدون اشتراك",
      periodMonthly: "تسعير مقطوع لكل عمل",
      periodYearly: "ادفع فقط مقابل ما تطلبه",
      desc: "صياغة مذكرات، عقود، وترافع قضائي متخصص — ادفع فقط عند الحاجة دون أي التزام سنوي",
      target: "أفراد",
      cta: "اطلب خدمة الآن",
      ctaHref: "/dashboard/client/draft",
      highlighted: false,
      color: "border-slate-300",
      isBetaHidden: false,
      features: {
        ai: [
          "استشارة مرئية مع محامٍ مرخّص (٣٠ دقيقة) = ٢٥٠ ر.س",
          "صياغة مذكرة رد / جوابية = ١,٥٠٠ ر.س",
          "مراجعة وتدقيق عقد = ٨٠٠ ر.س",
          "لائحة استئناف / نقض = تبدأ من ٣,٠٠٠ ر.س",
        ],
        platform: [
          "تمثيل قضائي وترافع مخصص من محامٍ مرخّص",
          "حجز الرسوم في محفظة الضمان المالي (Escrow)",
          "فحص تعارض المصالح والتدقيق المكتبي قبل التسليم",
          "لا يوجد أي اشتراك دوري أو رسوم خفية",
        ],
        support: ["متابعة مسار الطلب عبر المنصة", "تحديثات دورية حتى اكتمال الخدمة"],
      },
    },
    {
      id: "shield",
      isBetaHidden: true,
      name: "التأمين القانوني الفردي",
      badge: "ريال واحد يومياً · عرض التأسيس متاح",
      bonusLabel: "عرض التأسيس: ٢٩٦ ر.س/السنة الأولى لأول ٣٩٦ مشتركاً",
      priceMonthly: "٣٩",
      priceYearly: "٣٦٥",
      priceOriginal: "٣٦٥",
      periodMonthly: "ر.س / شهر",
      periodYearly: "ر.س / سنة (شامل الذكاء الاصطناعي)",
      desc: "غطاء قانوني وقائي متكامل طوال العام للمواطن والمقيم — حماية كاملة واستشارات معتمدة",
      target: "أفراد وموظفون ومستقلون",
      cta: "اشترك في التأمين الفردي",
      ctaHref: "/register/client?type=individual&plan=shield",
      highlighted: true,
      color: "border-blue-400 shadow-sm",
      features: {
        ai: [
          "ذكاء اصطناعي قانوني غير محدود طوال فترة الاشتراك",
          "استشهاد مباشر وفوري بمواد الأنظمة واللوائح السعودية",
          "فحص وقائي سنوي شامل لملفك القانوني والعقدي",
          "توليد ومراجعة مسودات الخطابات والإنذارات",
        ],
        platform: [
          "٣ استشارات قانونية سنوية (مرئية/هاتفية) مع محامٍ مرخّص",
          "مراجعة وتدقيق عقد واحد مجاناً سنوياً",
          "خصم مؤسس مستمر ١٥٪ على أتعاب الترافع وكافة القضايا",
          "قضية تمثيل مؤهلة واحدة بسقف أتعاب ١٠,٠٠٠ ر.س (بعد ٩٠ يوماً)",
        ],
        support: ["دعم فني وتوجيه إجرائي مباشر", "شارة عميل مؤسس لأول ٣٩٦ مشتركاً"],
      },
    },
    {
      id: "group",
      isBetaHidden: true,
      name: "التأمين القانوني الجماعي (الرَّبع)",
      badge: "٣–١٠ أفراد · وفر حتى ٥٥٪",
      bonusLabel: "خصم ٢٥٪ على الترافع + ٥ استشارات/عضو",
      priceMonthly: "يبدأ من ٦٥",
      priceYearly: "٧٥٠",
      periodMonthly: "ر.س / شهر للفرد في المجموعة",
      periodYearly: "ر.س / سنة للمجموعة (٣ أفراد)",
      desc: "حماية قانونية مشتركة للعائلة أو الأصدقاء — مزايا أعلى وسعر أقل لكل عضو، مع عزل كامل للخصوصية وضامن مالي موحد",
      target: "عائلات ومجموعات الأصدقاء (٣–١٠ أفراد)",
      cta: "ابدأ ربعك القانوني",
      ctaHref: "/dashboard/client/my-group?action=create",
      highlighted: false,
      color: "border-amber-400/80",
      features: {
        ai: [
          "ذكاء اصطناعي غير محدود واستشهادات نظامية لكل فرد بالمجموعة",
          "٥ استشارات مرئية سنوياً لكل عضو على حدة مع محامٍ مرخّص",
          "صياغة أو تدقيق عقدين (٢) سنوياً للمجموعة",
          "إمكانية الترقية من الفردي للجماعي مع خصم الرصيد المتبقي",
        ],
        platform: [
          "خصم ٢٥٪ على أتعاب الترافع والقضايا لكل عضو في المجموعة",
          "ضامن مالي موحد (Master Payer) يتولى السداد ويمنع التعثر",
          "تسعير مدرج: ٣ أفراد (٧٥٠ ر.س) / ٥ أفراد (٩٩٠ ر.س) / ١٠ أفراد (١,٦٥٠ ر.س)",
          "عزل تام للبيانات والاستشارات والقضايا لكل عضو (RLS)",
        ],
        support: ["أولوية قصوى على خط الدعم", "لوحة إحصائية للضامن لمتابعة استهلاك الحصص"],
      },
    },
  ],
  en: [
    {
      id: "pay-per-piece",
      name: "Pay Per Legal Work",
      badge: "No Subscription",
      priceMonthly: "Per Service",
      priceYearly: "0 SAR",
      periodMonthly: "Fixed fee per deliverable",
      periodYearly: "Pay only for what you need",
      desc: "Drafting briefs, contracts, and court representation — on-demand legal services without subscription commitments",
      target: "Individuals",
      cta: "Request Service",
      ctaHref: "/dashboard/client/draft",
      highlighted: false,
      color: "border-slate-300",
      isBetaHidden: false,
      features: {
        ai: [
          "Video consultation with a licensed lawyer (30 min) = SAR 250",
          "Statement of defense / reply brief drafting = SAR 1,500",
          "Contract review & legal audit = SAR 800",
          "Appeals & cassation briefs = Starts at SAR 3,000",
        ],
        platform: [
          "Full court representation by licensed Saudi attorneys",
          "Funds held safely in escrow until client approval",
          "Conflict-of-interest checks & internal quality gates",
          "Zero recurring fees or hidden charges",
        ],
        support: ["Real-time case tracking on platform", "Direct administrative updates"],
      },
    },
    {
      id: "shield",
      isBetaHidden: true,
      name: "Individual Legal Protection",
      badge: "1 SAR a Day · Founder Offer Available",
      bonusLabel: "Founding Offer: 296 SAR/1st yr for first 396 subscribers",
      priceMonthly: "39",
      priceYearly: "365",
      priceOriginal: "365",
      periodMonthly: "SAR / month",
      periodYearly: "SAR / year (Full AI included)",
      desc: "Comprehensive annual legal shield for citizens, residents & professionals — preventive protection & certified counsel",
      target: "Individuals, Employees & Freelancers",
      cta: "Get Individual Shield",
      ctaHref: "/register/client?type=individual&plan=shield",
      highlighted: true,
      color: "border-blue-400 shadow-sm",
      features: {
        ai: [
          "Unlimited legal AI assistance during active subscription",
          "Instant literal citations of Saudi statutory articles",
          "Annual preventive legal health check",
          "Drafting and review of official notices & letters",
        ],
        platform: [
          "3 annual consultations (video/voice) with licensed attorneys",
          "1 contract review & audit free per year",
          "Permanent 15% discount on litigation fees for all cases",
          "1 eligible representation case with SAR 10,000 fee cap (after 90 days)",
        ],
        support: ["Direct procedural support & guidance", "Founder Badge for first 396 members"],
      },
    },
    {
      id: "group",
      isBetaHidden: true,
      name: "Group Legal Protection (Al-Rabaa)",
      badge: "3–10 Members · Save up to 55%",
      bonusLabel: "25% litigation discount + 5 video consultations/member",
      priceMonthly: "From 65",
      priceYearly: "750",
      periodMonthly: "SAR / mo per member",
      periodYearly: "SAR / yr for group (3 members)",
      desc: "Shared legal coverage for families & trusted friends — greater perks and lower cost per person, with full privacy isolation and a single master payer",
      target: "Families & Friend Groups (3–10 members)",
      cta: "Start Group Shield",
      ctaHref: "/dashboard/client/my-group?action=create",
      highlighted: false,
      color: "border-amber-400/80",
      features: {
        ai: [
          "Unlimited legal AI and statutory citations for every member",
          "5 annual video consultations per member with licensed attorneys",
          "2 contract draftings or reviews per year for the group",
          "Seamless upgrade from individual plan with prorated deduction",
        ],
        platform: [
          "25% discount on court representation fees for all members",
          "Unified Master Payer guarantor preventing default",
          "Tiered pricing: 3 members (750 SAR) / 5 members (990 SAR) / 10 members (1,650 SAR)",
          "100% data & case privacy isolation between members (RLS)",
        ],
        support: ["Priority VIP support line", "Guarantor consumption dashboard"],
      },
    },
  ],
};

// ─── Comparison Tables: Individuals ──────────────────────────────────────────
export const comparisonIndividuals: { ar: ComparisonCategory[]; en: ComparisonCategory[] } = {
  ar: [
    {
      category: "الذكاء الاصطناعي والوقاية",
      icon: Brain,
      rows: [
        { feature: "الذكاء الاصطناعي القانوني",   "pay-per-piece": "محدود / تجريبي", shield: "غير محدود",            group: "غير محدود لكل فرد" },
        { feature: "الاستشهاد بالمواد النظامية",  "pay-per-piece": true,              shield: true,                 group: true },
        { feature: "فحص قانوني وقائي سنوي",       "pay-per-piece": false,             shield: true,                 group: true },
        { feature: "صياغة الخطابات والإنذارات",   "pay-per-piece": "حسب الخدمة",      shield: true,                 group: true },
      ],
    },
    {
      category: "المحامي المرخّص والتمثيل القضائي",
      icon: Gavel,
      rows: [
        { feature: "استشارات مع محامٍ مرخّص",    "pay-per-piece": "٢٥٠ ر.س/جلسة",     shield: "٣ استشارات/سنة",     group: "٥ استشارات/عضو/سنة" },
        { feature: "خصم أتعاب الترافع والقضايا", "pay-per-piece": "-",                shield: "١٥٪",                group: "٢٥٪" },
        { feature: "مراجعة وتدقيق العقود",       "pay-per-piece": "٨٠٠ ر.س/عقد",      shield: "عقد واحد مجاناً/سنة", group: "عقدان مجاناً/سنة" },
        { feature: "سقف الترافع المؤهل",          "pay-per-piece": "أتعاب متفق عليها", shield: "١٠,٠٠٠ ر.س (بعد ٩٠ يوماً)", group: "أولوية ترافع بخصم ٢٥٪" },
      ],
    },
    {
      category: "هيكل الاشتراك والمجموعة",
      icon: UsersThree,
      rows: [
        { feature: "عدد المشتركين",               "pay-per-piece": "فرد",             shield: "فرد واحد",           group: "٣ إلى ١٠ أفراد" },
        { feature: "طريقة السداد",                "pay-per-piece": "عند الطلب",       shield: "سنوي موحد",          group: "ضامن مالي موحد" },
        { feature: "عزل الخصوصية (RLS)",         "pay-per-piece": true,              shield: true,                 group: "١٠٠٪ معزول تماماً" },
        { feature: "إمكانية الترقية مع خصم الرصيد", "pay-per-piece": "-",              shield: "ترقية للجماعي فوراً", group: "توسيع عدد الأعضاء" },
      ],
    },
    {
      category: "التكلفة والدعم",
      icon: ShieldCheck,
      rows: [
        { feature: "سعر الاشتراك السنوي",         "pay-per-piece": "صفر ر.س",         shield: "٣٦٥ ر.س (عرض: ٢٩٦)", group: "يبدأ من ٧٥٠ ر.س (٣ أفراد)" },
        { feature: "متوسط تكلفة الفرد/سنة",       "pay-per-piece": "حسب الخدمة",      shield: "٣٦٥ ر.س",            group: "١٦٥ – ٢٥٠ ر.س/فرد" },
        { feature: "مستوى الدعم الفني",           "pay-per-piece": "دعم إجرائي للطلب", shield: "دعم مباشر + شارة مؤسس", group: "أولوية دعم قصوى" },
      ],
    },
  ],
  en: [
    {
      category: "AI & Preventive Law",
      icon: Brain,
      rows: [
        { feature: "Legal AI Queries",            "pay-per-piece": "Trial / Limited", shield: "Unlimited",          group: "Unlimited per member" },
        { feature: "Statutory Article Citations", "pay-per-piece": true,              shield: true,                 group: true },
        { feature: "Annual Legal Health Check",   "pay-per-piece": false,             shield: true,                 group: true },
        { feature: "Notice & Letter Drafting",    "pay-per-piece": "Per service",     shield: true,                 group: true },
      ],
    },
    {
      category: "Licensed Lawyers & Court Cases",
      icon: Gavel,
      rows: [
        { feature: "Lawyer Consultations",        "pay-per-piece": "SAR 250/session", shield: "3 sessions/year",    group: "5 sessions/member/yr" },
        { feature: "Litigation Fees Discount",    "pay-per-piece": "-",               shield: "15%",                group: "25%" },
        { feature: "Contract Review & Audit",     "pay-per-piece": "SAR 800/contract",shield: "1 free contract/yr", group: "2 free contracts/yr" },
        { feature: "Eligible Litigation Cap",     "pay-per-piece": "Agreed fee",      shield: "SAR 10,000 (after 90d)", group: "Priority with 25% off" },
      ],
    },
    {
      category: "Subscription & Group Architecture",
      icon: UsersThree,
      rows: [
        { feature: "Number of Members",           "pay-per-piece": "Solo",            shield: "Solo individual",    group: "3 to 10 members" },
        { feature: "Billing Mechanism",           "pay-per-piece": "On demand",       shield: "Annual upfront",     group: "Single Master Payer" },
        { feature: "Data Privacy Isolation (RLS)","pay-per-piece": true,              shield: true,                 group: "100% strictly isolated" },
        { feature: "Prorated Upgrade Option",     "pay-per-piece": "-",               shield: "Upgrade to group",   group: "Add more members" },
      ],
    },
    {
      category: "Pricing & Support",
      icon: ShieldCheck,
      rows: [
        { feature: "Annual Subscription Price",   "pay-per-piece": "0 SAR",           shield: "365 SAR (Offer: 296)", group: "From 750 SAR (3 members)" },
        { feature: "Average Cost/Member/Year",    "pay-per-piece": "Per service",     shield: "365 SAR",            group: "165 – 250 SAR/member" },
        { feature: "Support Level",               "pay-per-piece": "Standard support", shield: "Direct + Founder Badge", group: "VIP Priority Support" },
      ],
    },
  ],
};
